### ISSUE TITLE
System with no mouse hovers in the center

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#1002]
When there is no mouse present on the system (or even when there is but it hasn't moved), Conrod still thinks that it is at 0,0. If there is a button with a hover effect, this looks out of place.
![touch center](https://user-images.githubusercontent.com/3813500/27467227-fc898f9e-5823-11e7-952a-02153b4e17d4.jpg)

**Comment by mitchmindtree** [comment]
Ahh interesting. One way that you could fix this is by inserting a `MouseMove` input event (or whatever it is called) via the `ui.handle_input` method which moves the mouse to the corner of the screen or off screen before your main loop starts? Conrod itself does not have any control over the mouse position, however perhaps we can change the behaviour so that rather than defaulting to `0.0`, we use an `Option` and default to `None` until we receive the first mouse events?

**Comment by tl8roy** [comment]
Yeah, moving the mouse is Plan B. I think if it is easy enough, the Option pattern might be a nicer solution.

**Comment by mitchmindtree** [comment]
Seems to be closed by #1023
