### ISSUE TITLE
Button Presses not detected on a Touch Press

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#1003]
When a button is pressed on a touch screen, the button press effect doesn't trigger.

When the mouse button is pressed:
![mouse_down](https://user-images.githubusercontent.com/3813500/27467269-5547ac38-5824-11e7-9cc7-16c5a70cf234.jpg)

When the screen is tapped:
![touch_down](https://user-images.githubusercontent.com/3813500/27467268-55435598-5824-11e7-9bfd-1d131ad9e4b8.jpg)

**Comment by mitchmindtree** [comment]
Ahhh, I think this might be because these `Tap` events are "instantaneous" (e.g. the press and release are emitted at the same time). The `Button` widget as it currently works only displays a different colour *while* the press is occurring. Perhaps we could change the behaviour so that the button stays coloured for the frame that the button is released (this way taps should colour the button for a single frame).

**Comment by tl8roy** [comment]
I was fairly sure that winit emitted a touch start (Button down) and touch end (Button up) event. I would think that a solution could be to map these like the mouse.
