### ISSUE TITLE
Seems that gfx-rs backend is (slightly) broken

### ISSUE THREAD

**Issue by OtaK** [PistonDevelopers/conrod#1109]
Hey, I'm currently exploring other backends than glium, and I've tried the gfx-rs example, and I stumbled upon this error: 
<img width="1102" alt="capture d ecran 2017-12-14 a 15 29 46" src="https://user-images.githubusercontent.com/1262712/33997323-42b8b6c2-e0e4-11e7-84b6-8ab9c54a61d3.png">

Which I solved by just adding the required lifetime annotation in src/backend/gfx.rs

Anything I might have done wrong?
Any way to get a quick patch?

Thanks

**Comment by mitchmindtree** [comment]
Ahh thanks for the issue @OtaK, definitely a bug!

Perhaps for now we can just give it a `'static` lifetime to get it working? I just realised that the `gfx-rs` feature is missing from the travis' tests - no wonder I missed it!

**Comment by OtaK** [comment]
I just put a `GlyphCache<'a>` and added 'a as a lifetime on the holding struct and it worked, so it seems it would just work with any explicit lifetime marker.

**Comment by OtaK** [comment]
Submitted my fix, feel free to review it!

**Comment by lolgesten** [comment]
@mitchmindtree for conrod, is `gfx-rs` a lesser tested variant than `glium`? Since glium seem not developed anymore, I wondered whether to use glium or gfx-rs, but then I get worried to use a variant that less people use.

**Comment by mitchmindtree** [comment]
@lolgesten each of the backends tend to be maintained moreso by those that use them. I happen to use the glium backend most often as I find it easiest to use for my own projects, so I tend to invest more time into it. I'm generally happy to review and advise updates to the gfx-rs backend and will likely get around to adding features to it that are desired enough. FWIW there are still many users of glium as although the original author is not happy with some parts of the design, it is still perhaps the most accessible OpenGL-specific crate out there. It is mostly maintained by community contributions these days.

This issue is closed via #1110.
