### ISSUE TITLE
Very weird behaviour if "title"-(text)widget is removed from support/mod.rs

### ISSUE THREAD

**Issue by DancingBard** [PistonDevelopers/conrod#1184]
First off, I am on X11, Archlinux.

Now, I checked out conrod the other day and noticed some really, really weird behavior:

unaltered files:
`cargo run --features "winit glium" --example all_winit_glium` 

renders:

![unaltered_conrod](https://user-images.githubusercontent.com/26351327/42181515-644c4cbe-7e3b-11e8-98e4-183677d2fee7.png)

now, in `examples/support/mod.rs` I change *one* little line:
(https://github.com/PistonDevelopers/conrod/blob/master/examples/support/mod.rs#L147)

`    //widget::Text::new(TITLE).font_size(TITLE_SIZE).mid_top_of(ids.canvas).set(ids.title, ui);` (I added `//` before the line)

Now the example renders like this:

![altered_conrod](https://user-images.githubusercontent.com/26351327/42181523-6dab5278-7e3b-11e8-8e96-2dd906ec7dfd.png)

*The same happens with e.g.* `cargo run --features "winit gfx_rs" --example all_winit_gfx`

To me this is absolutely unexpected.
Removing the `title` alone, I would expect the `introduction` as well as the `image_title` and `rust_logo` **not to vanish** as nothing ever references the `title`-widget. This behaviour has cost me a sleepless night when incorporating https://github.com/PistonDevelopers/conrod/pull/1119 into my real application.

I would at least like to understand this :)

Am I misunderstanding something, or do we have a bug here?

**Comment by prismodestrux** [comment]
Windows 10 here, same issue:

![issue_windows](https://user-images.githubusercontent.com/11415460/42182076-741fc024-7e3d-11e8-866c-30f9160679b6.png)

**Comment by mitchmindtree** [comment]
Thanks for the issue, and sorry that you had sleepless nights as a result!

The `Ui` tracks what the previously instantiated widget is so that following widgets may describe their location relatively to whatever the last widget was. In this case, the [Text widget that follows the title text widget](https://github.com/PistonDevelopers/conrod/blob/master/examples/support/mod.rs#L158) specifies its position as `.down(60.0)`, meaning down from the previously instantiated widget. Once the title is removed, the previously instantiated widget becomes the `Canvas` which is the size of the window - as a result, the text widget ends up `.down(60.0)` from the `Canvas` (off the bottom of the window). The following widgets also disappear below the window for this same reason. I believe the PRESS ME button then appears in the middle due to [this line](https://github.com/PistonDevelopers/conrod/blob/master/examples/support/mod.rs#L270).

I totally agree that this is confusing behaviour, particularly if it's the first time that you come across it. It also makes it more difficult to refactor widgets (as you've already discovered). One alternative is to use the `.down_from(60.0, some_widget)` method, so that positioning may be specified relative to a specific widget (rather than the last set widget).

Another much better alternative that I've been meaning to implement for a while is an easier way of describing layout by subdividing areas of the window and automatically flowing widgets through these areas (a practise that is pretty common in a lot of web gui frameworks). This can already be done to an extent using `Canvas` (I think the `canvas` example demonstrates this) but I think it would be more useful if we also had some auto-flowing list widget - the kind where you can specify an area, a "gap" between widgets and a "flow" direction and it will automatically flow the contained widgets in that direction, wrapping them onto the next row/column as necessary. Unfortunately I simply haven't had time to get around to this!

Also w.r.t your first screenshot - it looks like the window is set to fullscreen on quite a large monitor? Perhaps you have a window manager which automatically sets fullscreen for the window? The example is made to initialise with certain dimensions (so that in terms of size it should look much closer to @prismodestrux screenshot). I think winit now allows specifying a fixed size, so maybe doing this would fix the window size behaviour on your setup?

**Comment by DancingBard** [comment]
@mitchmindtree first off: No, the window was not set to fullscreen, but it was nearly screen filling on an uhd monitor. Sorry if that has caused any confusion, I should've added a more appropriate screenshot!

Secondly, I am sorry for my inability to read the API then. It didn't occur to me, that this down could be the cause, I intuitively assumed that down meant, within the `parent` (which I assumed was `canvas` in this case, because it was set before. But then again, it totally makes sense now, as the following line again explicitly references the canvas!)

But again, entirely my fault, sorry again for wasting your time and many thanks for the explanation!
