### ISSUE TITLE
Examples fail to run on Manjaro linux.

### ISSUE THREAD

**Issue by zisisadamos** [PistonDevelopers/conrod#1277]
Although I am able to compile the source sucessfully. When I try to run the examples i get the following error.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NoAvailablePixelFormat)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Comment by mitchmindtree** [comment]
Thanks for the report!

Due to the `GlutinCreationError`, It looks like you're trying to use either the glium or gfx backends. This often occurs when attempting to enable a number of MSAA samples that is unsupported by the system. One thing you can try is to comment out the `.with_multisampling(x)` window builder method and try running it again.

**Comment by zisisadamos** [comment]
That did the trick! Thanks in all examples i just comment out .with_multisampling(x) and it runs okay.
