### ISSUE TITLE
Copyright status of fonts in assets directory

### ISSUE THREAD

**Issue by dlight** [PistonDevelopers/conrod#313]
Conrod distributes Arial.ttf, which I believe is copyrighted by Microsoft. Dense-Regular.otf, likewise, seems to be copyrighted by Charles Daoud:

    $ strings Arial.ttf|grep -i copyright
    "Copyright (c) 1997 Microsoft Corp.1
    (...)
    $ strings Dense-Regular.otf|grep -i copyright
    bCopyright (c) 2013 by Charles Daoud. All rights reserved.
    (...)

Fonts are copyrighted. One can generally redistribute a text using a given font without a license, but not redistribute the font itself. See for example [this](https://fedoraproject.org/wiki/Legal_considerations_for_fonts?rd=SIGs/Fonts/Legal) from the Fedora Wiki.

Microsoft [doesn't permit redistribution](http://www.microsoft.com/typography/faq/faq11.htm) of font files and at Charles Daoud's homepage, he offers the font "freely" but [without specifying a license](http://charlesdaoud.com/portfolio/dense-typeface/).

I suggest changing the fonts to one with an open license. Google Noto looks good and has glyphs for every language, in case someone needs internationalization. Other good options are Google Droid, Bitstream Vera, the DejaVu fonts, the Liberation font, the Ubuntu font, etc.

But anyway, the fonts are only used by the example - and well, Arial isn't even used.

Also, I think the proper way to deal with this is to completely wipe those files from the git history, but I see that it would be inconvenient for everyone (example: I'm not sure what `cargo update` would do)

**Comment by mitchmindtree** [comment]
Thanks a lot for the thorough head's up! I'm totally fine with changing to a properly licensed font - the current ones were thrown in early on without the expectation the project would draw so much attention. Now that the project's generating some attention we should definitely change over to something with a suitable license.

Does anyone have any nice OS font recommendations so that we can make the switch? If so, feel free to submit a PR with the change over :+1:

As for the git history, if anyone has any ideas on how to do this easily / smoothly, please chime in!

**Comment by bvssvni** [comment]
Licensing is always a problem with version control and ideally this should be taken care of beforehand. For example, there is a copy of these fonts now on crates.io and we have no power to remove them. Likewise, we can't remove the copies in the forks of Conrod. There is no excuse, and these files should be removed immediately even if leads to breakage.

If there is a smoothly way to remove them from git history, we will do so, but if there isn't, we have to make it practical and try to avoid further violations from this point on.
