### ISSUE TITLE
Move `CharacterCache` out of the `Ui` type?

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#375]
I just thought I'd open this issue for discussion - it may not be the best thing to do, but I thought it'd be useful to discuss alternatives in case we can come up with something (it'd also remove some type parameter noise from the ui.rs module).

The only reason the `CharacterCache` is stored within the `Ui` besides rendering is that it is currently needed to determine the dimensions of each character.

An alternative would be to use reasonable estimates for the dimensions of the characters based on the given font size and only pass the character cache in as an argument to the `.draw` method. I'm not yet sure how intertwined the character dimensions are in non-rendering logic and whether this is feasible - it would require some review first. Theoretically however, I can't think of a situation in which a widget should really need to know the exact size of the characters until the rendering stage.

**Comment by bvssvni** [comment]
For fonts that are not monospaced, you need to know the size of the characters to compute the location of a text cursor. I suspect that estimates is not good enough for this.

Sigh ... recently I've been thinking about all the trouble we get into because we try to avoid `Rc<RefCell<T>>`. The problem with passing `T` to any struct is that you don't know the size and therefore not how it will affect performance. Optimizing the size for complicated structs seems to be pretty hard for compiler optimization. If you need access to some shared mutable resource, then there are few options besides `Rc<RefCell<T>>`. On the downside you get a panic if you are not careful with borrowing, on the upside it is cheap to clone.

Perhaps passing `Rc<RefCell<C: CharacterCache>>` to the text widgets will solve the problem?

**Comment by mitchmindtree** [comment]
As of #433, the `Ui` wraps the `C: CharacterCache` in a `RefCell` within a custom `GlyphCache` type. Going to close this for now, will open a more specific issue for using a shared glyph cache if the use-case arises.
