### ISSUE TITLE
Auto-assign UIID to `<widget_name>::draw` functions.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#40]
At the moment, a unique UI_ID (User Interface ID) must be passed into each unique `<widget_name>::draw` call. This UI_ID is used by the `UIContext` to store the state for the associated widget and retrieve that state each time the draw function is called.

Currently, it is up to the user to make sure that they pass in a unique UI_ID for each widget that they draw (see the "all_widgets" example). This can be annoying for the user to keep track of, and makes it difficult to build parent widgets out of several child widgets, as each child may also require their own UI_ID.

An ideal solution would be to somehow automatically statically assign a unique UI_ID for every `<widget_name>::draw` call. Perhaps this is possible with a macro of some sort? Maybe one that generates a unique number every time it is called within code (I don't know if this is possible)?

This isn't an issue for retained-mode UI as the state is stored within unique widget structs meaning a `UIContext` is unnecessary. However, I'd much prefer we managed to solve the UI_ID issue, as in most cases retaining widget structs for every widget's state seems to be overkill, especially when almost all of their state can be procedurally derived from the data and context they are associated with anyway.

**Comment by bvssvni** [comment]
In 90% of cases you want to display a list of controls, and the same goes for interfaces on mobile platforms. I think unique numbers is fine for this.

**Comment by bvssvni** [comment]
Closing.

**Comment by viperscape** [comment]
Seeing how there is a desire for a [widgets-id macro](https://github.com/PistonDevelopers/conrod/issues/451), I think it would be beneficial if the uiids were generated and given as tokens for each widget. It can be complex to properly associate widget ids with their corresponding widget manually, especially if widgets are [dynamically created](https://github.com/viperscape/mush/blob/graph_backend/src/toolpane.rs#L56). Is it possible to store widget ids in the ui context, perhaps as a hashset?
I am considering a work-around but I'm not sure if it's possible to destroy a widget-id and mark for reuse, otherwise continually adding widget-ids during runtime will ultimately fail-- I assume; it's also overhead for the user, just as 'thinking about a coordinate system' would be.

Something like: 
``` rust
HashSet<(usize,u32)> //widget id, random::<u32>, though u64 might be better
```
This way instead of passing in uuid you would pass in the tuple, the actual uiid and its token to make unique. So when recycling a uiid, an outdated tuple is no longer appropriate and thus the uiid could safely be reused without checking against type_id equality. This would only work if a uiid could be recycled, which means it would have to be placed in a Vec<uiid> for later popping. All of this would have to work within its own structure of registered tuples. I think this would make creating a widget-id macro simple since the uiid referenced would not have to be any specific order, additionally the macro could be called multiple times/separately.

```rust
// with ui context
let my_button_id = ui.register::<WidgetId>(); // returns tuple
```

This obviously requires changes in conrod, which I am not fully sure is possible. How is the widget cache checked for the ids currently? This possible solution may not be appropriate, but it's a start-- I think it's definitely worth reconsidering because the overhead of managing widget-ids is too high.

**Comment by mitchmindtree** [comment]
Closing this as conrod now supports both static and dynamically created IDs.
