### ISSUE TITLE
Get ui mouse position

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/conrod#436]
ui.mouse was made private, and I see the free function get_mouse_state now but I don't know how to import the fn to use it; I must be missing something obvious! 

```
error: function `get_mouse_state` is private
use conrod::ui::{get_mouse_state};
```

**Comment by mitchmindtree** [comment]
Ahh sorry for the confusion, I must have forgotten about the change when I was writing the commit messages!

Each form of user input (mouse and keyboard) are now passed into each Widget's `update` method via a [`UserInput` param](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/button.rs#L139).

Also, now that the [internal widgets](https://github.com/PistonDevelopers/conrod/tree/master/src/widget) all implement the [`Widget`](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/mod.rs#L28) trait, they should be ok examples of how to go about implementing custom widgets. It's probably worth reading through the [`Widget` trait docs](http://docs.piston.rs/conrod/conrod/trait.Widget.html) as well as there have been a lot of significant changes since the `CustomWidget` trait was around.

Btw, the `mouse` module shouldn't be needed as it only contains two types and both are [exposed at the top level](https://github.com/PistonDevelopers/conrod/blob/master/src/lib.rs#L43-L44). Perhaps the internal widgets should also use them from the top-level to make them better examples.

I'll have to write up some more thorough docs on implementing custom widgets soon! For now, just let me know if there's anything else you run into :+1:

**Comment by viperscape** [comment]
Great, I see the floating canvas now :+1: , which really makes my point moot since that's what I was emulating :D I was originally pulling the coordinates outside of the widgets, during the render loop [like this](https://github.com/viperscape/mush/commit/ec2813ff51eef49c0a6e4a95d59a4da1843fadc5#diff-a0c94d0c1540ede7afa6f3cbdb8c8948R36)
Thanks!
