### ISSUE TITLE
Widget suggestion: List view

### ISSUE THREAD

**Issue by Izzeri** [PistonDevelopers/conrod#460]
I think this control is called a ListView or something similar in Windows. Basically a drop down list that is always expanded. Has a fixed size, and becomes scrollable if the entries in it take up more space than its height. Entries can be selected by clicking. Maybe allow selecting multiple entries?

**Comment by mitchmindtree** [comment]
I think we should be able to do this with the `DropDownList` widget - perhaps we could add an `.always_open(bool)` builder method?

**Comment by HitomiTenshi** [comment]
Personally I'd prefer having every widget do its thing. Having an `.always_open(bool)` in the `DropDownList` sounds logical but it doesn't feel right since the widget is supposed to `DropDown` as its name implies. I think it's better to create a `ListView` for that scenario, people will find it much more intuitive.

You know the Unix saying "Do One Thing and Do It Well", I think that should also apply to widgets. :smirk:

**Comment by cyplo** [comment]
+1 for the separate widget

**Comment by BenMcH** [comment]
If that is all that is needed to convert the drop down list to this list view, I'll work on this feature either Sunday night or Monday.

**Comment by mitchmindtree** [comment]
Just an idea - it might be simplest to implement this internally as a single `WidgetMatrix` with 1 column and *n* rows of `Button`s where *n* is the number of items in the list.

**Comment by BenMcH** [comment]
Hmm, I am unsure of what we should do and since I am VERY new to rust, I do not want to mess this up. I might return to this later.

**Comment by mitchmindtree** [comment]
There are now both [List](https://docs.rs/conrod/0.51.1/conrod/widget/list/struct.List.html) and [ListSelect](https://docs.rs/conrod/0.51.1/conrod/widget/list_select/struct.ListSelect.html) widgets that should satisfy this issue. Examples for each can be found in the `examples/` directory.
