### ISSUE TITLE
Canvas split issue: buttons show, not clickable

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/conrod#468]
With my [chess](https://github.com/viperscape/rust-chess) game, I noticed that when I used split canvas and render the [splits](https://github.com/viperscape/rust-chess/blob/master/examples/chess.rs#L92) based on a menu state; everything looks fine and works fine-- but when backing out to main screen the original canvas shows and its associated buttons show as they should, yet are unclickable/do not react.

State:
Main menu -> New Game and from there back out: Exit Game -> Main Menu, which shows as it did but the buttons are now not reacting as they should. I have checked to make sure the id's do not overlap-- so I am unsure what the issue is actually. Has anyone experienced this issue of non-reactive buttons? Any help is appreciate.

**Comment by mitchmindtree** [comment]
I think the issue here was that the `pick_widget` method (that determines what widget the mouse is currently over) was different to the render order, so in turn was a bit buggy, and didn't always register that widgets that were shown in previous frames are no longer being displayed. This should be fixed by #508 which implements a much more robust method for determining depth order, and this method is shared by both draw and pick_widget (so you should always be able to click anything that you can see.

Going to close this now, but let me know if you still have issues and I'll re-open :)
