### ISSUE TITLE
Create custom Widget examples.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#472]
I think the following would really help users design their own `Widget`s:
1. A simple as possible example of making and using a custom `Widget`.
2. An advanced example of using multiple pre-existing `Widget`s to design a single new `Widget`. This is probably difficult at the moment, but we should work to make this as easy as possible.

**Comment by m-bra** [comment]
This would help me too since I'm currently struggling creating a custom widget...
Using the internal widgets as reference does not work since they use other than just the `conrod` crate, for example to use `Scalar` one needs the `graphics` crate and I have no idea where to get that from

**Comment by jarrett** [comment]
I'm working on a new file in the `examples` folder that will illustrate custom widgets.

**Comment by jarrett** [comment]
I've added a custom widgets example on a [new branch](https://github.com/jarrett/conrod/tree/custom-widgets).

[Here's the example.](https://github.com/jarrett/conrod/blob/custom-widgets/examples/custom_widget.rs).

I had to [add some re-exports](https://github.com/jarrett/conrod/commit/313e618bf99d090ecf1dd6c9f23c3606f2233176#diff-b4aea3e418ccdb71239b96952d9cddb6) to the root module. That's because defining a widget requires some names that were previously private.

**Comment by mitchmindtree** [comment]
Closed by #525.
