### ISSUE TITLE
Move previous state (`prev`) in Widget::update

### ISSUE THREAD

**Issue by m-bra** [PistonDevelopers/conrod#492]
Currently, the signature of `Widget::update` looks like this:
`fn update(self, prev: &State<Self::State>, ...) -> Option<Self::State>`  
My problem is that `prev` is taken by immutable reference, thus, when creating the new state, it is impossible to move data from the previous state to the new state, which means everything has to be copied (or calculated).  
Wouldn't it be better if the previous state was taken by value, i. e. moved into the function?
`fn update(self, prev: State<Self::State>, ...) -> Option<Self::State>`
This way we can move some data from the previous to the new state directly, which is good when some parts of the state stay the same, especially if it is big data.

**Comment by mitchmindtree** [comment]
@m-bra thanks for the issue!

The problem I ran into here was that we need to know whether or not the updated state is different from the previous state so that we can know whether or not its `Element` needs to be re-drawn.

The idea there is that you return `None` from `update` unless some state has changed (in which case you return `Some(state)`), so you only have to construct the new `Self::State` if something has changed (normally only happens to whatever widget is currently being interacted with). This way the `Ui` knows that if `update` returns `Some` then it needs to draw the new `Element`, otherwise it can just use the pre-existing one.

If we're to pass the previous state with a `move`, then we need to either
- a. move the previous state out of the cache first so that we can pass it by value without cloning. We would then have to change the return type to just `Self::State` rather than `Option<Self::State>` so that the user can just return the prev state in the case that `update` wouldn't change anything (returning `None` would leave us without any state to use next time `update` gets called). One problem with this is that we no  longer know whether or not the state has changed after the `update` method as we only have the resulting state (and no previous state to compare it to). To avoid this, we could
- b. clone the previous state from the cache so that we can pass it by value, however this kind of defeats the purpose as the idea was to avoid having to allocate a whole new state in the first place. or
- c. return a `bool` alongside the state indicating whether or not the state has changed. This would mean we move the responsibility of checking whether state has changed from the lib onto the user, which may lead to unexpected errors/behaviour (perhaps this is worth it though? I'm not sure).

After going through all this, I ended up deciding it would probably be cheapest and easiest if we just passed in a reference to the cached state, and then only constructed a new state in the case that the `update` would actually return something new (which shouldn't be very often as the widget's state won't be changing unless interacted with).

I'm totally open to any PRs or drafts though! I suspect there's probably some nicer way of handling this than I'm currently able to think of atm :) Anyway, let me know your thoughts, hopefully the above isn't too confusing etc :+1:

**Comment by m-bra** [comment]
Thanks @mitchmindtree  for the fast reply and long answer and the good insight of the reasoning behind this!  

For widgets, which get not that often updated, I would happily use that method of updating them, since the construction of new states is not costly then. However, my widget is regularly updated and in this case, I would like to only update the necessary stuff. As it is now, I can only update everything or nothing (Returning `Some(..)` or `None`).  

These are some rough solutions for my case:
 * Decrease the rate of update of the state
 * The update, as it is now, is not suited for this case. Maybe I have to do it entirely different? Is there another way to implement my widget? I guess not, since there is only one widget trait
 * Change the way of handling the update, which is what I'd do, given that my proposal is any good ;)

What I want is to enable partial updates.  
This could be accomplished by:
 * Giving a mutable reference of the previous cached state to the update function, this way it can edit the state directly and as it wishes. It can leave some fields as they are and update some.
 * Moving the previous state into the update function, and having the function returning a state. This way it can reuse some parts of the previous state, or just return it directly without changing anything.  

I personally prefer the latter way because I think it's more elegant (it's more functional style :) ).  

However, either way we only have one state at all times, which means we can't compare the previous and next state so that we know whether we have to update the element of the widget.  
To solve this, we can:
 * Clone of the previous state before calling the update function and then comparing it to the result of the function
 * Have the function return a bool (in a tuple if alongside the other returns) which indicates whether the state has changed.  

I would not choose the first option, because we have to clone the state which takes time and space (if it is big data), and also because we have to compare afterwards (which also takes more time), which doesn't actually make sense because the update function knows whether he changed something or not, so why compare everything again?  
The problem with that is, as you stated, that the function then returns redundant information. Given the previous and new state, we can already know if there was a change. And this redundancy is dangerous, since then the result of the function may contradict itself, for example it could return a bool saying nothing changed but in reality the state *has* changed, and this contradiction leads to unexpected behavior.  
So we have to weigh out whether we want speed or safety if we only have those options I just named.

Or, another of doing it; to expand the option to give the update function a direct reference to the cached state:  
We can give the update function only a immutable reference by default, and if it wants to update the state it asks for a mutable reference. Whenever the update function asked for a mutable reference, we assume it changed it, thus we need to update the element.  
We could pass a callback to the update function which returns a mutable reference and sets a flag that it was called.  
This option might get a bit complicated for the user, but it depends on the way it is done!

So this is my problem and a few ideas to solve it, maybe I try to fork the project and play around a little if this is getting "serious". Otherwise I'd like to hear some opinions about that!   
Hope I can help!

**Comment by m-bra** [comment]
Also , when returning a bool to indicate a change, the update function has more fine-grained control on whether to update or not.

**Comment by mitchmindtree** [comment]
> We could pass a callback to the update function which returns a mutable reference and sets a flag that it was called.

@m-bra I really like this idea! I'm a bit busy to work on this myself at the moment, however I'd be happy to review a PR if you wanted to have a go at it yourself :+1:

**Comment by mitchmindtree** [comment]
Also out of curiousity, what is the Widget you're working on (if you don't mind me asking)?

**Comment by m-bra** [comment]
That's good! I can try to implement that and make a PR!Im working on a funcion plotter, which takes closures and can be "animated" e.g. involve time.

**Comment by mitchmindtree** [comment]
@m-bra Hi! Just thought I'd let you know that this has been addressed via #595 :+1:

Also, there's now a separate issue for "`set`ting widgets with arbitrary update rates" at #509
