### ISSUE TITLE
API consistency for inputting the WidgetId?

### ISSUE THREAD

**Issue by stratact** [PistonDevelopers/conrod#535]
Since I noticed that `Split::new()` requires the `WidgetId` for constructing, why not have the other widgets construct with the `WidgetId`, instead of waiting to input it in `.set()`?

For example:
`Button::new()` => `Button::new(id: WidgetId)`
`Label::new(text: &'a str)` => `Label::new(id: WidgetId, text: &'a str)`

I'm wondering why this wouldn't be a good idea, because I'm not sure if there are good reasons for requiring the `WidgetId` to be only inputted in `.set()` for the other widgets?

**Comment by mitchmindtree** [comment]
`Split`s aren't regular widgets (not like the others, anyway). It doesn't actually implement `Widget` itself, rather it is a "helper"/"wrapper" around the `Canvas` type to allow for easier, automated layout of canvasses (rather than setting the xy and dimensions manually). So under the hood, it actually [constructs a `Canvas`](https://github.com/PistonDevelopers/conrod/blob/master/src/widget/split.rs#L235) for each `Split` you create.

The reason most widgets leave the `WidgetId` to the `.set` method is
1. It's the only method required to be used by the `Widget` trait (otherwise we would have to add another method to get the `WidgetId` out of the widget somehow - might as well just pass it in `set`).
2. The `WidgetId` isn't actually needed at all until `.set` is called. This makes `.set`'s job a little more explicit and also means that widgets are more easily clone-able without aliasing their `WidgetId`s (however most widgets aren't clone-able anyway, due to their `.react` functions.. but we have some ideas for getting around this when some future rust features land).

Once upon a time we used to pass in IDs at the top as you suggest, but the current setup turned out to be easier/safer and a little more future proof :)

**Comment by stratact** [comment]
Good to know. Thank you for answering my questions. :smile:
