### ISSUE TITLE
Example to demonstrate state

### ISSUE THREAD

**Issue by jarrett** [PistonDevelopers/conrod#541]
I'm often finding that I need my widgets to consider arbitrary state from the application. I haven't yet settled on a design pattern that I like. So far I'm doing something like this:

    // In the main loop:
    MyWidget::new()
        .quux(&quux) // Arbitrary data from the app.
        .set(&mut ui, MY_WIDGET_ID)
    
    // In the widget's impl:
    pub fn quux(quux: &Quux) {
        self.quux = quux.clone();
    }
    
    // In Widget::update:
    let new_state = State {
      quux: self.quux,
      interaction: new_interaction
    }
    
    // In Widget::draw:
    let color = match state.quux {
        Quux::Bar => { red() }
        Quux::Baz => { green() }
    }

Is this how you'd recommend passing arbitrary state to a widget? It seems a little awkward, because both the widget struct and its `State` struct have the `quux` member. That duplication seems like a bad code smell, maybe. Or maybe this is how it's intended to work. Thoughts? Either way, I'd like to add a file to `examples` that demonstrates how to do this.

**Comment by mitchmindtree** [comment]
@jarrett in the `quux` method, I'd store a reference to `Quux` (instead of cloning) and then in `Widget::update`, I would compare the previous `State`'s `Quux` to the new `Quux` (using `!=`) and I'd only clone the new one in the case that it had changed since the last update (to avoid allocations). Storing it helps us to compare between updates and determine whether or not we need to call `draw` to construct a new `Element` again.

There's been [some discussion](https://github.com/PistonDevelopers/conrod/issues/492) on possibly passing in a function to mutate the current `State` (rather than always having to return a whole new `State`) which would both allow us to know whether the state has changed (by checking whether or not the mutate function was called) and avoid unnecessary allocations for larger widgets. I'm not sure if much has happened with it, but I'd definitely be open to the change though!

**Comment by jarrett** [comment]
Thanks!

Regarding the possible change: Would that require us to persist the widget
over the draw loop? (As opposed to reconstructing it each iteration as we
do now.)

**Comment by jarrett** [comment]
On a similar note, I'm confused about the `xy` method. It seems to come from `Positionable`, but that trait doesn't seem to be implemented for the widgets. For example, it's not in `label.rs`. What makes it possible to call `xy` on, say, a `Label`?

**Comment by mitchmindtree** [comment]
@jarrett The change wouldn't make any difference to conrod users, only to widget designers. It would mean the `Widget::update` method would allow widget designers to mutate the cached state when necessary rather than construct a new state altogether when some change is required.

`Positionable` is blanket implemented for all `T: Widget` (see `widget/mod.rs`).

**Comment by mitchmindtree** [comment]
Sorry for the late reply by the way, i've been sick for the past few days, getting back to work now :+1:

**Comment by mitchmindtree** [comment]
Follow up for anyone reading this:

We no longer return a new `State` from `Widget::update` - Instead we mutate the widget's `State` within the update. [Here's an example within the `EnvelopeEditor`'s update](https://github.com/mitchmindtree/conrod/blob/d2db8d0e986ac6888a0201c5bacfd867b875aa2e/src/widget/envelope_editor.rs#L389). Calling `state.update(|state| ...)` gives us a mutable reference to the widget's `State` while also indicating to the `Ui` that the widget has updated and in turn should be redrawn.
