### ISSUE TITLE
Support: Problems moving drawing with conrod w/o piston into helper methods

### ISSUE THREAD

**Issue by olsonjeffery** [PistonDevelopers/conrod#558]
I am using conrod without the piston event loop (really without most of piston, and more just straight-up gfx-rs and glutin) on OSX Yosemite, with rust nightly from August 17th.

I am running into a frustrating issue trying to move conrod boilerplate into a helper method. Normally, I have the `Ui<C>` and `Gfx2d` instances in the same scope as when I'm doing calls to do draws. I want to move that stuff out and pass in those things as parameters so that I can better encapsulate functionality and reuse it elsewhere.

Here is the build error I get:

```
bash-3.2$ cargo run
   Compiling game-proj v0.0.1 (file:///Users/jeff/src/game-proj)
src/client/main.rs:332:8: 332:19 error: type mismatch resolving `<gfx_graphics::back_end::GfxGraphics<'_, R, C, O> as graphics::graphics::Graphics>::Texture == gfx_texture::Texture<gfx_device_gl::Resources>`:
 expected type parameter,
    found enum `gfx_device_gl::Resources` [E0271]
src/client/main.rs:332     ui.draw(*c, g);
                              ^~~~~~~~~~~
src/client/main.rs:332:8: 332:19 help: run `rustc --explain E0271` to see a detailed explanation
error: aborting due to previous error
Could not compile `game-proj`.

To learn more, run the command again with --verbose.
bash-3.2$
```

Here is the code in question:

```
fn draw_loading<R, C, O>(ui: &mut Ui, state: &GameStateData, c: &Context, g: &mut GfxGraphics<R, C, O>) where R: Resources, C: CommandBuffer<R>, O: Output<R> {
    use conrod::color::{white};
    use conrod::{Colorable, Label, Positionable, Split};
    Split::new(MASTER)
        .rgba(0.0,0.0,0.0,0.0)
        .set(ui);
    Label::new(&state.misc.loading_msg)
        .color(white())
        .font_size(17)
        .middle_of(MASTER)
        .set(LOADING_LABEL, ui);
    ui.draw(*c, g);
}
```

I'm trying to figure out how I can configure the `g` parameter so that it'll satisfy what `Ui::draw` is expecting.

I actually have another conrod callback that seems to work alright:

```
type G2d<'a> = GfxGraphics<'a, gfx_device_gl::Resources, gfx_device_gl::CommandBuffer<gfx_device_gl::Resources>, gfx_window_glutin::Output<gfx_device_gl::Resources>>;

fn draw_fps(ui: &mut Ui, state: &GameStateData, c: &Context, g: &mut G2d) {
    use conrod::color::{white};
    use conrod::{Colorable, Label, Positionable, Split};
    Split::new(MASTER)
        .rgba(0.0,0.0,0.0,0.0)
        .set(ui);
    Label::new(&format!("{:?} fps", state.fps.fps))
        .color(white())
        .font_size(17)
        //.middle_of(CANVAS)
        .xy(450.0,-350.0)
        .set(FPS_LABEL, ui);
    ui.draw(*c, g);
}
```

But I have trouble calling this from my Ui/Gfx2d encapsulating helper method, because it can't convert the `g` provided by the callback function in `Gfx2d::draw` to something that satisfies the `G2d` typedef above _when placed in a helper method_.

Obviously there's something missing about how my type definitions are set up that I need to fix.

Any help would be appreciated! Thanks.

**Comment by olsonjeffery** [comment]
btw, in case you were curious.. this is my basic boilerplate to do a quick update for conrod from main:

```
    display_ctx.stream.clear(gfx::ClearData {color: [0.0, 0.0, 0.0, 1.0], depth: 1.0, stencil: 0});
    {
        state.misc.loading_msg = "Setting up scripting engine".to_string();
        let (renderer, output) = display_ctx.stream.access();
        display_ctx.g2d.draw(renderer, output, state.misc.viewport, |c, g| draw_loading(&mut ui, &state, &c, g));
    }
    display_ctx.stream.present(&mut display_ctx.device);
```

yuck.

**Comment by mitchmindtree** [comment]
@olsonjeffery I realise it's been a long time and that you have probably moved on since, however I just thought I'd provide an update as conrod has changed a lot over the last year and many of these issues should no longer apply.

The `glutin_glium.rs` example demonstrates how to use conrod without any of the piston dependencies (the main loop is just `loop` with a call to `sleep` at the end for simplicity). There is also a `glutin_gfx.rs` example, however it is currently messy and unfinished, i.e. not all `render::Primitive`s are being rendered and the boilerplate hasn't been moved into a backend feature yet. It should be pretty easy to do this following the `glium.rs` backend module as an example.

This [blog post](http://blog.piston.rs/2016/09/13/this-year-in-conrod/) provides some more info on these changes and much more. In general a lot of work went into making conrod easier to encapsulate and easier to use with non-piston backends.
