### ISSUE TITLE
What is the expected behaviour when I have conrod and gl at the same time?

### ISSUE THREAD

**Issue by liquidmetal** [PistonDevelopers/conrod#562]
I was trying out some code today and came up with this (based entirely on all_widgets.rs):
https://github.com/liquidmetal/seq-view/blob/master/src/main.rs#L122-L124

The behaviour I'm seeing right now is:
- It renders the background color as specified in the `clear` command
- The `draw_ui` method draws the label for the first time
- Every subsequent frame only has the background color

tl; dr: Label shows for only one frame and then vanishes.

I'm not sure if this is expected. Am I doing something wrong?

**Comment by mitchmindtree** [comment]
This is occurring because [here](https://github.com/liquidmetal/seq-view/blob/master/src/main.rs#L122) you use the `clear` function from the `graphics` crate (which will redraw every frame) instead of `conrod`'s `Background` widget (which, when using `draw_if_changed` as you are, will only redraw whenever something within the `Ui` changes).

You can fix this by either using `Background` ([as seen here](https://github.com/PistonDevelopers/conrod/blob/master/examples/all_widgets.rs#L169)) instead of `clear` (the recommended way) or by using `.draw` instead of `.draw_if_changed` which will redraw the `Ui` every frame (but consume more cpu as a result).

**Comment by mitchmindtree** [comment]
Going to close this now, feel free to re-open if there's still an issue :+1:

**Comment by liquidmetal** [comment]
Thanks! This makes sense and I was able to use `.draw` to get things working.
