### ISSUE TITLE
Widgets centered on first frame

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#655]
In Turbine, when starting the application the widgets seems to be centered at the first frame, and then corrected at later frames.

Code:

```Rust
        if !capture_cursor {
            use conrod::*;
            
            ui.handle_event(&e);
            e.update(|_| ui.set_widgets(|ui| {
                Button::new()
                    .color(color::blue())
                    .top_left()
                    .w_h(60.0, 30.0)
                    .label("refresh")
                    .react(|| {})
                    .set(REFRESH, ui);
            }));
            e.draw_2d(|c, g| {
                ui.draw(c, g);
            });
        }
```

**Comment by bvssvni** [comment]
I tested with rendering 20 buttons, and the effect was more visible.

Believe I saw this once in one of the Conrod examples, but the effect is harder to notice here since the window is appearing in the same moment. In Turbine, you notice it when pressing C after the window has loaded.

**Comment by bvssvni** [comment]
Printing out rectangle and color in `draw_from_container`:

```Rust
        primitive::shape::framed_rectangle::KIND => {
            if let Some(framed_rectangle) = container.unique_widget_state::<::FramedRectangle>() {
                let frame = framed_rectangle.style.get_frame(theme);
                if frame > 0.0 {
                    let frame_color = framed_rectangle.style.get_frame_color(theme);
                    let frame_rect = container.rect;
                    draw_rectangle(context, graphics, frame_rect, frame_color);
                }
                let color = framed_rectangle.style.get_color(theme);
                let rect = container.rect.pad(frame);

                static mut i: u32 = 0;
                println!("{:?}", rect);
                println!("{:?}", color);
                unsafe { i += 1; if i > 5 { panic!(""); } }
                draw_rectangle(context, graphics, rect, color);
            }
        },
```

Getting:

```
Rect { x: Range { start: 0, end: 0 }, y: Range { start: 0, end: 0 } }
Rgba(0, 0, 0, 0)
Rect { x: Range { start: 1, end: 59 }, y: Range { start: -29, end: -1 } }
Rgba(0.28509036, 0.41999847, 0.66608846, 1)
Rect { x: Range { start: -512, end: 512 }, y: Range { start: -384, end: 384 } }
Rgba(0, 0, 0, 0)
Rect { x: Range { start: -511, end: -453 }, y: Range { start: 355, end: 383 } }
Rgba(0.20392157, 0.39607844, 0.6431373, 1)
Rect { x: Range { start: -512, end: 512 }, y: Range { start: -384, end: 384 } }
Rgba(0, 0, 0, 0)
Rect { x: Range { start: -511, end: -453 }, y: Range { start: 355, end: 383 } }
Rgba(0.20392157, 0.39607844, 0.6431373, 1)
thread '<main>' panicked at '', /Users/sven/rust/conrod/./src/backend/graphics.rs:206
```

**Comment by bvssvni** [comment]
This draws one blue rectangle on top of a black rectangle. I printed out first `context.transform` to see if the matrix was wrong, but it was the same. Seems to be the rectangle that is calculated wrong first time.

**Comment by mitchmindtree** [comment]
Hmmm strange! Thanks for the details, will have a look into it now.

**Comment by bvssvni** [comment]
Tested with `cargo run --example hello_world` in Turbine. Still the same problem.

**Comment by mitchmindtree** [comment]
I did test a few times and thought it was no longer occurring, however after testing again a few times I did just notice it.

My hypothesis:

The way turbine currently captures the cursor is by only passing *any* events to conrod when the cursor is not captured by turbine - this means that conrod doesn't get any window size information until the first time conrod gets a `draw` event while the cursor *isn't* captured by turbine. This results in the `Button` being placed on a `Window` of size (0.0, 0.0) for the first frame that the `Ui` is drawn (and thus, placed in the centre of the screen). This isn't technically a bug in conrod as it is designed to be passed all events on all occurrences, but it shows that this behaviour is non-obvious and it highlights the importance of addressing #613 so that there is a proper API for external capturing of input.

In the mean-time, this could be fixed by *only* blocking mouse events (rather than all events) from conrod while turbine captures the mouse, rather than blocking all events as is currently the case. i.e. something like
```rust
if !(capture_cursor && e.is_mouse_event()) {
    ui.handle_event(e);
}
```

I'll leave this open for you to close once you can confirm that this fixes the issue on your end.

**Comment by bvssvni** [comment]
I'm sending just the render events, since the other events that Conrod handles should be ignored when not active. See https://github.com/PistonDevelopers/turbine/pull/42
