### ISSUE TITLE
Can't update Texture of an Image

### ISSUE THREAD

**Issue by fb39ca4** [PistonDevelopers/conrod#725]
Since `Image` requires the texture to be wrapped in an `Arc`, there is no way to mutate the original texture. Could conrod implement another way of drawing a texture that allows for mutability?

**Comment by mitchmindtree** [comment]
Perhaps we could find a way to make `Image` a little more generic?

I think the reason I originally chose `Arc` was so that `Texture`s could be stored within the `widget_graph` (so that it can be drawn when `ui.draw(...)` is called) without requiring any new allocations. I think this is especially useful when using the same Texture between multiple widgets. However, I think your use case is also quit obviously important!

I think there's a lot of possible options to support here such as `Arc<T>`, `Arc<Mutex<T>>`, `Rc<T>`, `Rc<RefCell<T>>`, `T` or some other custom type (i.e. that might use channels to receive functions that update `T`, etc). Perhaps the best option would be to provide some trait that has a method returning a `&Texture`?

**Comment by fb39ca4** [comment]
I don't know enough about Rust to comment on the pros and cons of those approaches, but I can see that the current Image works well for static graphics and should be kept, because of the optimizations that can be made. So perhaps have a separate DynamicImage primitive instead?

**Comment by bvssvni** [comment]
There is an `Arc::make_mut` method which clones the image if there are more than one reference.

**Comment by fb39ca4** [comment]
I've tried that, but `Image` does not have the `Clone` trait.

**Comment by pierrechevalier83** [comment]
I've got the same problem as @fb39ca4 : I need to update the texture of an Image for a project.

I wouldn't mind to try and implement it, but I think I would need a bit of a starter.

For example:
@mitchmindtree : "Perhaps the best option would be to provide some trait that has a method returning a &Texture?"
Could you expand on this?

**Comment by mitchmindtree** [comment]
Hey @pierrechevalier83, thanks for chiming in!

As we speak I'm working on #734, in which I'm hoping to address this issue with the `Image` API. The PR proposes an overhaul of the way conrod widgets are rendered, so it makes sense to tackle this at the same time. I foresee a couple options - I'll lay my thoughts out here as it would be great to get some feedback before making a decision!

1. A conrod-specific `Image` trait
----------------------------------

Rather than taking an `Arc<T>` where `T: ImageSize`, we could design a simple, conrod-specific trait. Something like:

```rust
pub trait Image: std::any::Any {}
```

We could provide the following implementations:

```rust
impl<T: Image> Image for Rc<T> {}
impl<T: Image> Image for RefCell<T> {}
impl<T: Image> Image for Arc<T> {}
impl<T: Image> Image for Mutex<T> {}
```

We could add `Ui::image` and `Ui::image_mut` methods so that the user can access their `Image` types however they need between widget instantiations, something like:

```rust
/// Borrow the image of type `T` from the `Image` widget at index `I`.
fn image<I, T>(&self, idx: I) -> Option<&T>
    where I: Into<widget::Index>,
          T: Image,
{
    self.widget_graph.widget(idx)
        .and_then(|w| w.unique_widget_state::<Image<T>>())
        .map(|u| &u.state.image)
}

fn image_mut<I, T>(&mut self, ...
```

The `render::Primitive::Image` variant (in the new `render` API introduced by #734) could contain a borrow of the actual image data type `T`. 

**Pros**

- Requires minimal constraints on Image types
- Users can access images mutably/immutably when needed

**Cons**

- Requires that the `Ui` owns an instance of the `Image` type (not a big deal if the user doesn't mind using `Rc` or `Arc`).
- The user would be required to specify the `Image` type used `Ui::draw`, i.e. `ui.draw::<T>()` so that it may be cast from `Any` (the type it is stored as).
- All image types used with `Image` widgets instantiated from the same `Ui` instance would have to be of the same type. The user could however make their own wrapper enum and use that instead.

2. Using `ID`s (instead of generic types)
-----------------------------------------

Rather than taking some generic `Texture` type, one option might be to have `Image::new` take some `texture::Id` (a `u32` identifier) which the user can map to the correct `Texture` when `Ui::draw` is called. 

**Pros**

Neither the `Image` nor the `Ui` will require ownership over the texture, and in turn will not imply any bounds on the types of textures that may be used. This should also hopefully leave the user free to update their textures however they wish between calls to draw. It may also remove the need for adding extra indirection (i.e. `Box`, `Rc` or `Arc`) depending on the user's case.

**Cons**

My main concern with this method is that it still doesn't solve how to implement new custom `Widget`s that instantiate their own `Image`s. I.e. If I want to make a `RustButton` widget that has the Rust logo on it, there's no way to make sure that the image is drawn unless we require that the user of the widget instantiates the texture, creates an ID, passes the ID to our `RustButton::new` constructor and then maps the ID to the texture and draws the texture (seems like a massive pain).

**Comment by pierrechevalier83** [comment]
Thanks for the fast and comprehensive answer, @mitchmindtree.

First of all, thumbs-up for #734: It seems like it's taking the conrod code base into a cleaner direction with better defined abstractions. "Following this PR we can think of conrod as a pipe where conrod::event::Raws are the input and conrod::render::Primitives are the output." As a core of the library (after hiding some of it from the user with friendly abstractions), I think that's a very clean mental picture to have.

Now for my feedback for the image trait (to take with a grain of salt: I'm relatively new to Rust and to Conrod).

I like your first suggestion.
The two pros you listed: any image type works and mutable/immutable access is possible are the core of what I need as a user.

Also, I don't have a problem with the UI owning the image:
As a user, I want to build up the UI giving it what it needs: fragments of text, textures, shape and layout info, you name it. The UI can own all these things and show me a visual representation. I won't need to do anything else with the textures. The reason I built them in the first place was for the UI to represent them. Lon story short, I think it's a perfectly acceptable contract to have between user and UI.

For the two other flaws you list: having to specify the type of image in draw and having to draw the same kinds of image though the UI, I think it's more of a problem. For my particular use case, it would be OK; but in general, I think it would be nice to find a way around it.

Even with this con, I prefer option 1 to option 2:
Having the user own the textures and give conrod a set of IDs to access them seems to me like a bit of a messy interface. I think it will lead to a more confusing mental model for the user. "The UI needs a bunch of texture, so I create them, give them each an ID and give the UI the ID so it can access them while I own them and do nothing else with them..." It doesn't seem as straightforward to me as option 1.
I think creating a "RustButton" widget should be a first class citizen use of conrod.

Anyway, just my two cents. Thanks for the great work! I'll be keeping an eye on #734 :)

**Comment by mitchmindtree** [comment]
@pierrechevalier83 totally, I agree with all of this, I've also been leaning towards 1 myself since last night. I've spent the morning implementing these changes and I've just about finished, however there are a couple things that are still bugging me about this approach:

1. Trying to find a nice way to ensure the user passes the correct type to `ui.draw::<T>()` that doesn't require propagating the `T` parameter across the  `Ui` and `UiCell` types and `Widget` trait. The main problem is that the user could easily call `ui.draw::<T>()` with a different type than the type that they used to instantiate their `Image`s. We could handle this by either:
    1. silently omitting the `Primitive::Image` whose data failed to cast to `T`
    2. `panic!` and provide the index of the `Image` widget that could not be cast to `T`
    3. have `Primitive::Image` variants contain a `Result`, with an `Err` for failed casts

    None of which are particularly nice solutions, especially considering this should probably be handled at compile time. This bug would probably occur pretty frequently, considering a user could easily change the type of image they're using in their `Image` widget instantiations but forget to change the parameter given to the `Ui::draw` call.

2. Although the `Ui` owns the image data within the graph, the user still needs to hold onto a copy of the same data due to the immediate widget API. I.e. as `Image::new(user_image)` is called once every update, the user would still require holding a copy of the `user_image`.

Possible Solution - `image::Map<T>`
--------------------------------------------

Perhaps we could store all images in a separate type,  called the `image::Map<T>`. The `image::Map<T>` could be constructed by the user during the setup stage (before the main program loop begins) and could map `widget::Index` of `Image` widgets to user images. So internally, it might hold a `std::collections::HashMap<widget::Index, T>` where `T` is some user image. We could provide a macro that simplifies construction of the map:
```rust
let image_map = image_map! {
    RUST_LOGO: Arc::new(image::open("rust-logo.png")),
    CAT_PIC: Arc::new(image::open("floof.jpeg")),
    // etc
};
```

The `image::Map` could deref to the internal `HashMap` so that entries may be borrowed, mutated, added, removed, etc as necessary.

The `Ui::draw` method could take an `&image::Map<T>` argument so that the necessary `&T` may be yielded along with each `Primitive::Image` variant.

**Pros**

- Solves **1.** as the type of the image data can be given to the `Ui::draw` method directly by the image map argument (don't have to worry about casting to types).
- Solves **2.** as the `Image::new` constructor would no longer need to take any parameters at all, as its `widget::Index` is already mapped to the `Image` that it will display.
- Solves the previous `texture::Id` issue where the user would have to manually map IDs to textures (instead, we provide a map type and the user uses existing `widget::Index`s rather than introducing another ID type).

**Cons**

- Still leaves the issue of how to create custom widgets that instantiate their own `Image` widgets internally. These custom widgets would require access to the `image::Map` in order to add their own mappings. Using the `RustLogo` widget example I gave in my previous comment, instantiation might look something like this:
    ```rust
    RustLogo::new(&mut image_map)
    ```

    while the implementation might look like this:

    ```rust
    if !image_map.contains_key(&child_image_idx) {
        image_map.insert(child_image_idx, image::open("rust-logo.png"));
    }
    ```

    Come to think of it, I suppose this really isn't too bad.

- A user might instantiate their `Image` widget but forget to add their image mapping to the `image::Map`. This means we still need to decide whether the `render::Primitive::Image` variant should either hold `Option<&'a T>` or `panic!` if no mapping exists within the `image::Map`. I think `Option<&'a T>` is probably the best bet here as it still gives the option of manually `panic!`ing i.e. `image.expect("No mapping found")`. Probably not that significant an issue.

**Comment by pierrechevalier83** [comment]
@mitchmindtree, these are valid objections.
For objection 1., I would say that as long as we fail explicitely (as suggested in 1.ii. or 1.iii.), it wouldn't be that big a deal for a user. With good documentationa dn a meaningful error message, they would figure it out.
I think objection 2. is more worrying: I hadn't realised this when I posted my first comment, but indeed; the ownership isn't as well defined as I thought.

I guess image::Map is a possible solution. I agree that the pros are pretty convincing. I don't find the cons you gave to be blockers either.
I have another con to add though:
**Con**
Building an Image::Map with the image_map! macro prevents you from adding a collection of images conveniently.
Let me give an example: my use case is to represent a deck of cards.
I can build a map<Card, Texture> internally where a Card has a Value and  Suit. I can do that looping between my folders in assets assuming they're named consistently.
If I then have to map these textures to some Id, I'll have to manually spell out all the cards in the deck.
I think there may be other usecases where you really don't want to manually enumerate all textures you will use in the app.

**Hybrid approach**

Now I've got an alternative suggestion that kind of meets halfway. It may make no sense at all. Please let me know if I'm missing somethign major.

What about we internally take a map of images, but without showing it to the user?
We could change Image::new() to take an Option<Image>.
The "indexing" can be done with the actual widget Id.
When we draw the image, the first time, if we're passed None, we can panic! with "missing texture"
On subsequent calls to Image::new(), if we get None, we use the texture in our hashmap that is associated to that widget.
Finally, if we already have a texture in our hashmap for that widget but we get Some(image), we can update the texture in there.

**Pros**
* Fixes issue 2.: The caller doesn't need to hold onto the image anymore.
* Makes creating custom image based widget easy again
* Fixes my objection: collection of images don't have to be manually listed

**Cons**
* Doesn't solve issue 1., although I would argue that's OK as long as we fail explicitely with a comrehensive error message.
* Maybe it would feel a bit strange to be passing an optional texture to Image::new(). I guess it would need to be well documented at least.

**Comment by mitchmindtree** [comment]
@pierrechevalier83 just to clarify, the `image_map!` macro would not have to contain all images that may be used throughout the duration of the program - it would just be a helper constructor for the case where the user has a lot of static images that do not change, which I imagine might be the case for many users.

In your case where you have a collection of card images and you'd like to change which image is displayed from a specific `Image` widget, you could initially construct your map with
```rust
let mut image_map = image::Map::new();
````
and then assign the new image by doing something like:
```rust
image_map.insert(CARD_IMAGE, new_card_image);
```
where `CARD_IMAGE` is the `WidgetId` for your `Image` widget that displays the card. Now the `CARD_IMAGE` widget will display your `new_card_image`.

If you'd like to extend the `image::Map` with a new collection of cards and their associated widget indices, you could even do something like this:
```rust
image_map.extend(image_widget_ids.zip(card_images));
```
where `image_widget_ids` is some iterator yielding the widget index for each `Image` widget you'd like to display your new card images, and `card_images` is the collection of new card images.

**Comment by mitchmindtree** [comment]
Another benefit to the `image::Map` is that we can easily automatically track when images have been mutated, swapped, added, etc and in turn require redrawing. The `Map` could contain a `needs_redraw: bool` field which is set to `true` any time a mutating method is called and resets to `false` after `ui.draw` is called.

**Comment by pierrechevalier83** [comment]
@mitchmintree, you convinced me: I am now leaning towards the image map option.
