### ISSUE TITLE
How I may use the Factory inside a Custom Widget?

### ISSUE THREAD

**Issue by gallexme** [PistonDevelopers/conrod#728]
What I would like to do in my Widget is to Draw a always changing Image
to make a Image u need the Factory(for Texture)
but Widgets dont have access to any Factory do they?

what i want to try:

```

 buffer = ImageBuffer::from_raw(screen.width() as u32,
                                       screen.height() as u32,
                                       screen.as_ref().to_vec())
            .unwrap();
         Image::from_texture(Arc::new(Texture::from_image(factory,&buffer,
        &TextureSettings::new())
         .unwrap()))
         .set(image_idx, &mut ui);
```

**Comment by gallexme** [comment]
anyone?

**Comment by mitchmindtree** [comment]
Hey @gallexme, sorry for the late reply, only just noticed your issue here!

Support for `Image`s is still very new and incomplete. The way that images are currently implemented impose a lot of limitations (i.e. requires conrod to know about generic `Texture` types, updating an image is very difficult, etc).

I have a [WIP PR](https://github.com/PistonDevelopers/conrod/pull/734) that will change image instantiation to use IDs instead of generic params as well as provide the user with much more control over the way their primitives are rendered. This way, conrod will impose less constraints over the types of images that may be used, and should be more flexible when it comes to integrating images into other types of widgets. Users should also be able to more easily take advantage of techniques like instancing this way. I'm hoping to get around to finishing the PR soon, but am a little busy with other work at present. Thanks for the issue in any case!

**Comment by mitchmindtree** [comment]
#734 is now merged and should resolve this issue, so going to close this for now. Feel free to keep commenting or re-open if you're still running into issues :+1:
