### ISSUE TITLE
Draw the remaining `render::Primitive`s within the `glutin_glium.rs` example

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#752]
In #734 conrod introduced a more flexible method of rendering in a "backend agnostic" manner. Instead of requiring a constrained graphics backend, conrod now simply renders the entire `Ui` as a list of `render::Primitive`s.

#734 also introduced a `glutin_glium.rs` example in order to demonstrate this flexibility and demonstrate how to use conrod with glutin and glium directly. The PR correctly handles `Text`, however the other `Primitive`s are not yet handled.

- [x] `Rectangle`
- [x] `Lines`
- [x] `Polygon`
- [x] `Text`
- [ ] `Image` Could probably take inspiration from the way `Text` is rendered.

**Comment by clicketyclack** [comment]
I did some experimentation in a seperate branch:[28b0c79](https://github.com/clicketyclack/conrod/commit/28b0c79f0e48e6c3a4df6d879e2ae799c68e87e1)

I added some code to handle polygons, [glutin_glium.rs#L158](https://github.com/clicketyclack/conrod/blob/28b0c79f0e48e6c3a4df6d879e2ae799c68e87e1/examples/glutin_glium.rs#L158) but left the vertices-pushing code below at [glutin_glium.rs#L245](https://github.com/clicketyclack/conrod/blob/28b0c79f0e48e6c3a4df6d879e2ae799c68e87e1/examples/glutin_glium.rs#L245).

Do we want to convert `Line` primitives to triangles before sending into glium? Otherwise my conclusion is that we'll need some way of switching the GL draw mode (TriangleList, LineStrip) etc before sending in the vertexes for each conrod primitive. I see a few different approaches:

 - Moving the glium calls on lines 245-253 to the end of the `PrimitiveKind::Text` block at [glutin_glium.rs#L227](https://github.com/clicketyclack/conrod/blob/28b0c79f0e48e6c3a4df6d879e2ae799c68e87e1/examples/glutin_glium.rs#L227), then implementing new glium calls in each of the match cases.
 - Switching `vertices` to some sort of `glium_queue` vector where each item would be a `GliumQueueEnum`, such as a vector of vertices, a color change command, etc.  This is the same approach as the `Command enum` in  #809.

Using `TrianglesList` vs `LineStrip`:
![image](https://cloud.githubusercontent.com/assets/22734483/19628285/a4889674-995a-11e6-8339-3987b1206a5b.png)

**Comment by clicketyclack** [comment]
@mitchmindtree Am I correct in assuming that the render loop from `examples/glutin_glium.rs` should be moved to `src/backend/glium.rs` later on?

**Comment by mitchmindtree** [comment]
Oh awesome! Thanks heaps for looking into this - exciting stuff :)

> Switching vertices to some sort of glium_queue vector where each item would be a GliumQueueEnum, such as a vector of vertices, a color change command, etc. This is the same approach as the Command enum in #809.

I'm not experienced enough with GL to know which option would be the most efficient performance-wise, but I feel like this option is probably the cleanest in terms of API :+1: I like the idea of providing a pipe-like function in the `glium` backend which takes the `render::Primitives` as input and produces a list of glium-specific enum variants like you mention as output. This way we can still make it very easy for the user to draw the primitives while still giving them control over the actual drawing :+1:

> Am I correct in assuming that the render loop from examples/glutin_glium.rs should be moved to src/backend/glium.rs later on?

Yeah exactly :+1:

**Comment by clicketyclack** [comment]
Guess I should post an update. It's turning into a monster.
 [glutin_glium.rs](https://github.com/clicketyclack/conrod/blob/glium_fish_polygon/examples/glutin_glium.rs)

Current appearance is below. 
![image](https://cloud.githubusercontent.com/assets/22734483/19833771/6ff0aa50-9e46-11e6-9c9e-2ce8fa88c372.png)

Few points:
- Polygons are filled now, but concave ones have issues. I.e. the fin "armpits" are unintentionally also filled.
- The colors are temporarily wacky because of debug purposes.
- There are 4 orientation triangles on each side, also for debug purposes.
- The top right widget is a `widget::Image`. I added my own texture because `rust.png` is black-on-transparent. Those two colors make trying to figure out GL shader coloring very confusing.
- A few widgets unintentionally use the glyphcache texture. I think it's interesting how it orders the glyphs by height. Also the cache is mostly blank.
- The top left widget is a `widget::Circle`. Seems to work.
- The fish polygon can not be moved or scaled.
- Under it is a `widget::Toggle`. There is no label support.
- Bottom right is a 200px wide, 50px high button. Obviously something wrong there.
- The canvas background is always square. Resizing the window shows the purple glium background.

![image](https://cloud.githubusercontent.com/assets/22734483/19833895/760c7c8a-9e4a-11e6-863b-34ca2d7b5fe8.png)

**Comment by mitchmindtree** [comment]
Haha wow, this is looking like some kind of abstract early-net era artwork 💯 Awesome job on making it this far :+1:

Perhaps it'd be a bit easier to make clearer progress on this if we have a "correct" version of the example to compare it to...

I've been thinking that we could re-do the `all_widgets.rs` example (so that it *actually* uses all widgets) and then use this as the GUI for both the `glutin_glium.rs` and `glutin_gfx.rs` examples. By this, I mean we add a module to the `examples/` directory that contains a demo `App` type and a `gui` fn which could then be re-used in each of the examples. This way we can compare the one drawn with piston to the `glutin_glium.rs` and `glutin_gfx.rs` ones and ensure that the behaviour is correct over each of them. Also saves us from having to come up with new abstract widget artworks to test the `glutin_glium.rs` and `glutin_gfx.rs` examples 😉 

I might have a look into this later today.

**Comment by clicketyclack** [comment]
Yup, very placeholder-ish for now. I can simplify the poly, perhaps a textured half-moon? Or something more asymmetrical? Btw, I think the fish is flipped. The two fins were on the bottom when I inkscape:ed it. Could be an export issue though.

We def. need a better test texture long-term too, showing off all R,G,B,A channels. The shader in trunk clobbers the G and B channels!

Would also like some lines in the `all_widgets`. I'm uncertain about how we want the line end caps should look.

I probably won't commit anything until the weekend.

**Comment by clicketyclack** [comment]
Weekly progress report...

Done: 
 - Merge in changes from #851 .
 - Add texture/color mixer weight into shader, so we can set vertexes to color vs texture again. 
 - Fix various artefacting. 
 - Implement basic lines support in renderer.

Todo / bugs:
 - Understand / convert glyphcache 1-channel texture vs RGBA.
 - Why are the ball coords treated as outlines?
 - Close polygons (i.e. indent in bottom left one)
 - Why is the BG color different?
 - Get better at handling more textures. Convert shader uniform to `SrgbTexture2dArray`?

Glium on left, `examples/all_widgets` on right.
![image](https://cloud.githubusercontent.com/assets/22734483/20041102/9c89efa8-a464-11e6-8c98-d99bc47c3fc7.png)

**Comment by mitchmindtree** [comment]
Hey @clicketyclack, nice work :+1:

I had a look at your code and attempted to clean it up a bit and re-write some parts to make it a little more efficient and address some of the bugs. Here's some screenshots of my progress (taken from my retina display):

<img width="718" alt="screen shot 2016-11-08 at 1 04 44 am" src="https://cloud.githubusercontent.com/assets/4587373/20060703/8100d20a-a550-11e6-9225-8f449d28bf53.png">

<img width="718" alt="screen shot 2016-11-08 at 1 04 37 am" src="https://cloud.githubusercontent.com/assets/4587373/20060695/795b791a-a550-11e6-9e68-c25414e1999c.png">

<img width="718" alt="screen shot 2016-11-08 at 1 05 01 am" src="https://cloud.githubusercontent.com/assets/4587373/20060710/8681c1b2-a550-11e6-88b0-484914bfd17b.png">

<img width="718" alt="screen shot 2016-11-08 at 1 05 25 am" src="https://cloud.githubusercontent.com/assets/4587373/20060717/8c46a0a4-a550-11e6-91c0-cad597a77dc6.png">

Think I managed to address most of your points! The fork is [here](https://github.com/mitchmindtree/conrod/blob/glutin_glium_example/examples/glutin_glium.rs) if you're interested.

I only have a couple steps left but I'll probably leave them for tomorrow:

- Work out why the rust logo isn't renderering.
- Triangulate line joins properly and handle line cap.
- Handle `scizzor` properly.

After I've done those, I'll move what I can into nice abstractions within the `backend/glium.rs` module and then do a PR 👍
