### ISSUE TITLE
`backend::piston::draw`: Text rendering is blurry and displays artifacts on hi-DPI displays.

### ISSUE THREAD

**Issue by sp-1234** [PistonDevelopers/conrod#787]
After running `cargo run --release --example all_widgets` with current commit (82f0a1b13f7858721ad6c0add6f366fb909df630), this is how it looks:
![screen shot 2016-08-12 at 16 24 40-fs8](https://cloud.githubusercontent.com/assets/19407943/17623613/8df817d4-60a9-11e6-821e-2ffbc2dd8d12.png)

Look at 1:1 zoom to see what's exactly wrong.

BTW, it also doesn't react to cmd+Q, not sure if it's by design.

**Comment by mitchmindtree** [comment]
Hey thanks for the issue @sp-1234, appreciate it!

I notice this on my retina too. I believe the problem is the `draw` implementation for the piston backend [here](https://github.com/PistonDevelopers/conrod/blob/master/src/backend/piston/draw.rs#L172). The piston-graphics crate provides a DPI agnostic API that uses `Scalar` positioning values in most places, however in the `Image` API it only allows us to specify integer position values when describing the source rectangle (the part of the image to render). This is a problem for hi-DPI displays as many of the source rectangle positions might lie between integer values, so when piston scales up by a DPI-factor of 2.0 the resulting source rectangle can be up to a whole pixel out of position. Our best bet would probably be to make the fix upstream (by changing the source rectangle to use `Scalar` positioning), test to ensure that this is indeed the case and then submit a PR to the piston-graphics crate.

Alternatively, if you test the `glutin_glium.rs` example you should hopefully see that the text renders nicely on retina, as well as a lot nicer as it takes advantage of the GPU cache properly. However, the text primitive is the *only* primitive being rendered so far in that example as I still need help finishing the remaining ones (I'm still new to GL and glium).

Re cmd+Q not working: this is not by my design. I'll have to test the glutin examples to see if this is the case for all glutin apps, or if there's something going on in the pistondevelopers/glutin_window wrapper (used by piston_window in most of the examples) that prevents it.

**Comment by sp-1234** [comment]
I think it should be fixed because it scares newcomers who happen to trip on this on first sight

**Comment by magicgoose** [comment]
text is now OK
