### ISSUE TITLE
Canvas example: tabs take 6 seconds to switch in debug mode

### ISSUE THREAD

**Issue by Boscop** [PistonDevelopers/conrod#824]
When running the canvas example in debug mode (on Windows 8.1), it takes about 6 seconds from clicking one of the tabs (FOO, BAR, BAZ) until the tab actually changes. (In release mode it's near instantaneous.)

**Comment by christolliday** [comment]
This is solved for me by my pull request: https://github.com/PistonDevelopers/conrod/pull/831

This looks to be a performance issue caused by the matrix of buttons at the bottom of the canvas example taking a lot of work to update. On my machine, with the polling event loop, this example takes 100% CPU. It seems like the draw calls get delayed as it works to catch up with all the update calls in between. I profiled it and the biggest chunk of work is done by `matrix::Element::update`

Using a waiting event loop skips enough work for this to be responsive, but it still uses ~50% CPU in debug mode when moving the mouse around inside the window.
