### ISSUE TITLE
"Autocolor" chooses white text on white background in some cases (bug in all_widgets.rs example)

### ISSUE THREAD

**Issue by Boscop** [PistonDevelopers/conrod#827]
When you start the all_widgets example and select 0.79 for blue and 0.71 for red and 0.0 for green, the widget containing the "border width" text will have white text on white background.
When you increase the red value above that level, the envelope editors will have white lines/points on bright green (and the "height" widget has white text on bright green bg), making it less readable than black on bright green IMO.

![conrod_bug_white_text](https://cloud.githubusercontent.com/assets/535593/18405897/95851b9c-76f6-11e6-8e31-7565bc9f4a3a.png)

Btw, I'm not sure what the best way is to calculate a complemetary color, but this seems to be interesting:
http://gamedev.stackexchange.com/questions/38536/given-a-rgb-color-x-how-to-find-the-most-contrasting-color-y

**Comment by mitchmindtree** [comment]
Currently we provide a `color.plain_contrast()` method which kind of does this - it returns white if the color's luminance is under 0.5, or black if the luminance is greater than 0.5. Most of the other widgets are using this in the example I believe, we might just have to change the number dialers to do this too.

We also provide a `color.complement()` which returns the color with the hue rotated 180 degrees.

**Comment by clicketyclack** [comment]
Will look into this...

**Comment by clicketyclack** [comment]
Playing around a bit. It occurs when any slider combination adds up to 1.5. (.71+0+.79,  .5+.5+.5 etc). Or simply if the average bg color is 
0.5.

The reason for white-on-white is because the box bg color and text color is:
`box_bg_color = window_bg_color.average().abs()`
`box_text_color = window_bg_color.average().invert().abs()`

where
`window_bg_color.average() -> 0.5`
`0.5.abs() -> 1.0`
`0.5.invert().abs() -> (1 - 0.5).invert() -> (0.5).abs() -> 1.0`

So the white-on-white issue is only due to all_widgets.rs. I'll still update the plain_contrast() method since white-on-green is a bit bright.

**Comment by clicketyclack** [comment]
Fixed in #844.
