### ISSUE TITLE
Text primitive prevents Textedit from recieving input other than backspace.

### ISSUE THREAD

**Issue by Morindhal** [PistonDevelopers/conrod#833]
In my <a href="https://github.com/Morindhal/socketmessenger">very basic implementation</a> of conrod having a text prevents my textedit from being able to get any key-events other than backspace if the text is before textedit, if the text is after the textedit (as is right now) I can edit the textedit as expected.

conrod = "0.44.0" <-- is the version this is a issue for me on.

Ps. This is my first opened issue on GitHub so please let me know what I should have mentioned.

Also, with before and after I mean which line of code the widgets are on.

**Comment by mitchmindtree** [comment]
Hey @Morindhal, would you mind sharing the code where you instantiate both widgets (or your whole GUI code if possible)? Might give us a clue as to what's going on. Does the `text_edit.rs` example work for you btw? I'm having trouble thinking of why a `Text` widget would interfere with a `TextEdit`'s keyboard input off the top of my head.

**Comment by Morindhal** [comment]
The code I use it the one I <a href="https://github.com/Morindhal/socketmessenger">linked to</a>, in src/main.rs simply move the textedit that starts at line 120 to below the text widget that starts at line 132 and it stops working.
The text_edit.rs should work fine for me as I only have a problem with it if a text widget is introduced before the textedit.

**Comment by mitchmindtree** [comment]
@Morindhal ahh, I think this might be because the height is not set for the `TextEdit` in your first set of parameters mentioned in your edit, so the `TextEdit` disallows inserting any more text in order to not exceed its dimensions. In the second set of parameters (that you mention work as intended), the height is given as the height of the `Text` that it is placed on top of, so the `TextEdit` has enough space to enter some text.

Ideally, we should probably make it so that the `TextEdit`'s height defaults to the height of its `font_size` if none is specified by the user. For now however,  you might be able to get around this by either:
- Setting the height of the `TextEdit` as you do in your second example above or
- Calling `.restrict_to_height(false)` on the `TextEdit` widget. I think this will continue to wrap the text to the width, but will allow the text to trail off the bottom of the widget, even if it would exceed the total height of the widget.

Let me know if that helps! If not, I'll have a closer look at the code you linked soon.

**Comment by Morindhal** [comment]
@mitchmindtree, I used the .restrict_to_height(false) approach and it works for me, I'll just add a scroll-bar there later.
Thanks for the help, this thing was driving me nuts, heh.
