### ISSUE TITLE
Use traits from Piston core instead of PistonWindow

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/conrod#835]
I want this because the piston_window crate is just a wrapper for easy setup, not intended for libraries to depend on it.

**Comment by echochamber** [comment]
Did you mean "from" instead of "for"?

**Comment by mitchmindtree** [comment]
To clarify, conrod doesn't directly depend upon `piston_window`, other than by providing a helper function via the feature-gated backend module to make it slightly easier to use for drawing. The examples do use it, but only because it is easy to setup as you mention. Do you think the examples might benefit from using the traits instead of piston_window anyway?

**Comment by bvssvni** [comment]
It would be nice if you could use Conrod without any boilerplate. For example, if I want to use the Sdl2 window backend it is not easy to change it (I think).

**Comment by mitchmindtree** [comment]
It should be easy to make that change now - just a matter of swapping out piston_window for sdl2_window + one of the graphics backends (and using `conrod::backend::piston` instead of `conrod::backend::piston_window`). Or are you talking about using sdl2_window *with* piston_window? In that case, I think `conrod::backend::piston_window` just assumes the default piston_window parameters, so that might not be as easy, but I imagine it would be an easy fix in `conrod::backend::piston_window` to add the window generic back.

Either way, hopefully we'll be able to get rid of the drawing `backend` modules in conrod if PistonDevelopers/graphics#1053 works out.

**Comment by mitchmindtree** [comment]
Going to close this as it is no longer really relevant. For anyone reading this feel free to see #909 for related discussion.
