### ISSUE TITLE
#[derive(Debug)] not sprinkled all over

### ISSUE THREAD

**Issue by ksf** [PistonDevelopers/conrod#839]
Pretty much title. The lack of `Debug` impls for even transparent plain old data makes `print!`-debugging or even just poking to gain insight rather awkward, to put it mildly.

**Comment by mitchmindtree** [comment]
Feel free to add the impl where you find it necessary and submit a PR :+1:

Compilation already takes a long time, I normally hold off on arbitrarily adding impls like this until someone comes across a specific need for them, as you have.

**Comment by azriel91** [comment]
Turns out I need this for `Ui`, and long story short, we need the following repositories/crates to be updated in order:

* https://github.com/dylanede/stb_truetype-rs
* https://github.com/dylanede/rusttype
* this one (conrod)

I'll link the PRs as I can make them (need to update Cargo.toml for each crate that is published)

**Comment by shanehandley** [comment]
I'll assume that with #961 closed via #1234 , this can be closed.
