### ISSUE TITLE
Conrod readme.md doesn't have complete example

### ISSUE THREAD

**Issue by AaronM04** [PistonDevelopers/conrod#860]
Hi. This crate looks very promising, but I can't seem to get a standalone app to work that uses it. I suppose after a few days, I could figure it out. It would be really helpful to newbies such as myself if the README.md contained a complete working example (Cargo.toml + main.rs) that just opened up a window and displayed Hello World or something.

Thanks for the great work.

**Comment by mitchmindtree** [comment]
Hey thanks for the feedback @AaronM04, much appreciated!

The repository includes an `examples/` directory that includes a variety of examples demonstrating different widget and GUI features.  Are any of these close to what you're looking for? The `glutin_glium.rs` and `all_widgets.rs` might be closest to what you're looking for - they demonstrate how to instantiate a variety of widgets and use them to update your application state.

You're probably right though, it might be best to have a more obvious example front and center in the `README.md`, as many folk won't dig much deeper if they can't see an immediate example? I also still need to finish chapter 3 of the guide which will probably help a lot with this. So much to do! 😩 But we'll get there 😸 

Hope this helps, let me know if you run into any more issues :+1:

**Comment by AaronM04** [comment]
@mitchmindtree the examples help, but they're all part of the conrod repository and it's not obvious how to make them into standalone projects. In particular, I can't figure out a working `Cargo.toml` that will let me compile the `all_widgets.rs` example. Great work by the way! :)

**Comment by mitchmindtree** [comment]
@AaronM04 thanks!

Ahh I see what you mean, perhaps this [getting started guide](http://doc.crates.io/index.html) for cargo might help? It describes the standard way to setup projects and add dependencies.

If there are any particular issues you're running into with setting up you're `Cargo.toml`, maybe I could help? I guess the main thing is making sure the necessary dependencies are listed (you can infer these by checking what `extern crate`s are used in the example) and that the versions match those that are listed in conrod's `Cargo.toml`.

**Comment by AaronM04** [comment]
@mitchmindtree Try to compile this test project: https://github.com/AaronM04/conrod_test

The main.rs is taken from one of your examples. It's unable to find some structs inside `conrod::backend::piston`.

**Comment by mitchmindtree** [comment]
@AaronM04 hey there, the problem is that your conrod dependency is set to version `"*"` which means "whatever the latest version is, even if it is a breaking change". Since this code was copy-pasted, conrod has gone through an update or two and as a result this code has stopped compiling.

I would recommend using a set version for conrod in your `Cargo.toml` (i.e. the current is `"0.46.2"`) to avoid accidentally updating to a version that would break when you are not ready for it. Conrod is pre-1.0.0 and still undergoing development so small breakages are still common between minor versions. We try our best to never break between *tiny* versions though.

I'd recommend re copy-pasting the primitives example and setting your dependency versions to the current versions.

**Comment by AaronM04** [comment]
@mitchmindtree That worked! I updated https://github.com/AaronM04/conrod_test in case you want to see. Thank you!

**Comment by mitchmindtree** [comment]
No problem!
