### ISSUE TITLE
Image Button Issues

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#861]
With the Image Buttons, I am having a few issues.

Firstly, when a label is added, it is positioned under the image. Additionally, the image resizes to the width of the label.

Secondly, sometimes when the button is clicked, a dark background appears.
![conrod image button](https://cloud.githubusercontent.com/assets/3813500/20254296/a69d9e84-aa7e-11e6-892c-f141c5f888bf.png)

        // Button widget example button.
        if widget::Button::image(ids.img_dark_blue_button)
            .w_h(BUTTON_WIDTH_ARROW, BUTTON_HEIGHT_ARROW)
            //.mid_bottom_of(ids.background)
            .color(color::TRANSPARENT)
            //.floating(true)
            .border(0.0)
            .label("Testing")
            .label_color(TEXTWHITE)
            .label_font_size(32)
            //.image_color_with_feedback(color::RED)
            .set(ids.button, ui)
            .was_clicked()
        {
            println!("Yay!");

        }

**Comment by mitchmindtree** [comment]
Thanks for the report, definitely looks like a bug! Support for images on `Button`s was only added recently, so might still need some cleanup. I'll look into this later on tonight.

Btw, are you using the `piston` backend feature (the default) or the `glium` backend feature for drawing the `Ui`? It might help to know this if the issue turns out to be back-end specific, though I doubt it will.

**Comment by tl8roy** [comment]
Piston backend.

**Comment by mitchmindtree** [comment]
Woops, closed wrong issue
