### ISSUE TITLE
Image Washed Out in Glium Backend

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#867]
I changed from Piston to Glium for performance reasons.

I have found however that the background image is washed out.
The dark version is what is intended.

Image and background colour
![conrod image bg](https://cloud.githubusercontent.com/assets/3813500/20333832/35583ade-ac01-11e6-9d80-6d93fc72fb89.png)

Just the background colour
![conrod image none](https://cloud.githubusercontent.com/assets/3813500/20333833/357bf5c8-ac01-11e6-8b26-932325ec1412.png)

Raw image used
![background](https://cloud.githubusercontent.com/assets/3813500/20333839/3d40dfa8-ac01-11e6-875e-a3bf1500b32f.png)

All the image loading is the same as the glium_glutin example. Here is the widget creation.

    widget::Canvas::new().color(BGCOLOUR).set(ids.background, ui);
    // Instantiate the `Image` at its full size in the middle of the window.
    widget::Image::new().w_h(WIDTH as f64, HEIGHT as f64).top_left().set(ids.background_logo, ui);

**Comment by mitchmindtree** [comment]
Hmmmm I wonder if changing the type of glium texture that you load the image as will help.

Rather than loading the image to a `Texture2d` (like in the `glutin_glium.rs` example) could you try loading it to a [`SrgbTexture2d`](http://tomaka.github.io/glium/glium/texture/srgb_texture2d/struct.SrgbTexture2d.html)? Should be able to just replace `Texture2d` with `SrgbTexture2d`. I don't have a lot of experience with `glium` myself, but it looks like the problem might be the way that gamma is handled for the texture. Let me know how it goes.

**Comment by tl8roy** [comment]
Yep, that fixed it. 

I was fixing another issue with Glium and saw the difference between rgb and srgb and thought that might have something to do with it.

**Comment by mitchmindtree** [comment]
I'll close this for now and make a mental note to change the `glutin_glium.rs` example to use `SrgbTexture2d` to avoid other users running into the same issue via copy pasta.

**Comment by Boscop** [comment]
I have a similar problem:

I'm loading faces of a cubemap into a `Texture2d` and then filling the faces of the cubemap like this:
```rust
let (image, w, h) = load_jpeg("images/posx.jpg");
let image = RawImage2d::from_raw_rgb(image, (w, h));
let tex_posx = Texture2d::new(&display, image);
let posx = SimpleFrameBuffer::new(&display, cubemap.main_level().image(CubeLayer::PositiveX));
tex_posx.as_surface().blit_whole_color_to(&posx, &dest_rect1, MagnifySamplerFilter::Linear);
```
but the cubemap is way too bright when I render it, I think it's because the images are sRGB, so i tried to do `let tex_posx = SrgbTexture2d::new(&display, image);` instead, but it fails to compile, because it doesn't have the method `as_surface()` that `Texture2d` has:
<https://docs.rs/glium/0.27.0/glium/texture/texture2d/struct.Texture2d.html#method.as_surface>
Any idea how I can do this? :)
