### ISSUE TITLE
Examples do not update window size at startup

### ISSUE THREAD

**Issue by Yoda12999** [PistonDevelopers/conrod#873]
Each of the examples expects to start with a certain window size and is able to be resized from there. This is fine, until you are in an environment where the window size requested is not necessarily given, such as with tiling window managers. When the starting size at startup is not what was expected, text and graphics can be wildly offset from their expected position. Resizing the window manually fixes the issue. I have specifically seen this with i3, but would imagine that it would happen with other tiling window managers as well.

**Comment by mitchmindtree** [comment]
@Yoda12999 thanks for the report!

Hmmm this is a tricky issue, as conrod can only track window dimensions via either the initial ones passed to `Ui` instantiation, or via `Input::Resize` events passed to the `Ui::handle_event` method.

If the user cannot determine the dimensions of the window to which the `Ui` will be drawn before instantiating the `Ui`, I would recommend submitting a `Input::Resize` event via the `Ui::handle_event` method as soon as they have access to this information, preferably before `Ui::set_widgets` is called for the first time. I think this should avoid the wild offsets you mention.

Would this work around be suitable in your case at all? If so, perhaps it could be beneficial for us to add this as a note within the `Ui::new` documentation.

**Comment by mitchmindtree** [comment]
> This is fine, until you are in an environment where the window size requested is not necessarily given, such as with tiling window managers.

Thinking on this further, perhaps this is also an issue that should be considered upstream at [tomaka/glutin](https://github.com/tomaka/glutin) (the library used for managing and polling events from the window in all of the examples). If the window is created with an initial size (as we do in the examples) and these dimensions are immediately discarded in favour of those given by the tiling manager, then perhaps glutin should probably either:

- create a `glutin::Event::Resized` with the actual dimensions and yield this as the first polled event or
- return an Error explaining why the window couldn't be created with the given dimensions
- change the `WindowBuilder::with_dimensions` method to `with_desired_dimensions`

Otherwise, the user will always be required to manually check the value at `display.get_window().unwrap().get_inner_size().unwrap()` after window creation regardless of their call to `with_dimensions` in order to support tiling. Maybe this is reasonable anyways? I think my personal preference would be for glutin to emit an `Event::Resized` though I haven't thought it through very far yet.

**Comment by Yoda12999** [comment]
The more I think about it, I also agree that this should probably be handled by glutin as it is in charge of the window at the basic level. I will look at moving this conversation over to there when I have a little time look into their examples and submit a new bug report.

**Comment by Yoda12999** [comment]
Running the examples included with glutin does not show the problem seen with the conrod examples. Specifically, each example draws to the entire window (or pane, or whatever i3 likes calling them) whereas the conrod examples require the window to be resized before they use the entire window.This may be because the glutin examples do not set a window size when creating the window.

It apears that there is a resize event sent at start in the glutin examples, though I have not had time to look into if conrad gets a similar event and if it is being masked by the setting of the window size during initialization.

**Comment by mitchmindtree** [comment]
@Yoda12999 ahh interesting. Does conrod's `glutin_glium.rs` example show this same bug? That example is unique in that it uses a conrod-specific `glutin` and `glium` features, rather than using `glutin` via the `piston` feature like the rest of the examples. I'm just wondering whether the bug might be specific to the way glutin has been wrapped in piston's `glutin_window` wrapper crate.

**Comment by Yoda12999** [comment]
`glutin_glium.rs` works without problems.

**Comment by TimBednarzyk** [comment]
I think the following code in the `glutin_glium.rs` example is why that example works fine. This code is in the main loop:
```
            // We must manually track the window width and height as it is currently not possible to
            // receive `Resize` events from glium on Mac OS any other way.
            //
            // TODO: Once the following PR lands, we should stop tracking size like this and use the
            // `window_resize_callback`. https://github.com/tomaka/winit/pull/88
            if let Some(win_rect) = ui.rect_of(ui.window) {
                let (win_w, win_h) = (win_rect.w() as u32, win_rect.h() as u32);
                let (w, h) = display.get_window().unwrap().get_inner_size_points().unwrap();
                if w != win_w || h != win_h {
                    let event = conrod::event::Input::Resize(w, h);
                    ui.handle_event(event);
                }
            }
```

**Comment by mitchmindtree** [comment]
@TimBednarzyk hopefully we'll be able to remove that snippet if [this](https://github.com/tomaka/winit/issues/20) goes ahead - it should address the issue on OS X where resize events are not emitted among other things.

**Comment by mitchmindtree** [comment]
Going to close as this as I feel the original issue is probably more suited to [tomaka/winit](github.com/tomaka/winit) than it is to conrod.

Meanwhile, the code snippet that @TimBednarzyk has since been removed as it should be unnecessary following tomaka/winit#118.
