### ISSUE TITLE
scroll wheel scrolling is abominably slow on all_widgets example

### ISSUE THREAD

**Issue by Kingsquee** [PistonDevelopers/conrod#878]
Steps to reproduce:
1) ```cargo run --release --example all_widgets```
2) try to use the scroll wheel to scroll down
3) observe the text scroll down one pixel at a time
4) turn mouse over and treat it like a wind up racecar

Fedora 24, Xorg, GNOME Shell 3.20.4

**Comment by mitchmindtree** [comment]
@Kingsquee ahh thanks for pointing this out - I believe this is because the `glutin_window` crate (used via the `piston_window` crate which is currently used in many of the examples) translates `glutin::Event::Scroll::LineDelta`s into single pixel adjustments, when they should really be propagated as `LineDelta`s so that the users can configure how much of a jump a single line delta is equivalent to. I might close this issue in favour of the upstream PistonDevelopers/glutin_window#69 issue.

In the meantime, the `glutin` feature (which can be tested via the `glutin_glium.rs` example) should handle this much better as the `glutin` feature translates the line delta to a more reasonable scalar delta. That said, it's still not as good a solution IMO as adding a `LineDelta` variant to the `Input` enum that we use.

**Comment by Kingsquee** [comment]
glutin_glium is definitely more usable! thanks for taking the time.
