### ISSUE TITLE
envelopes in old_demo mistakenly create new dots on left-mouse release

### ISSUE THREAD

**Issue by Kingsquee** [PistonDevelopers/conrod#880]
Steps to reproduce:
1) ```cargo run --release --example old_demo```
2) hold down on a dot inside one of the envelopes
3) quickly flick mouse a short distance while releasing button 
4) if the dot being dragged is far enough away during the previous frame, a new dot will be created where the mouse was released, as if one had pressed there

while this is called old_demo, I'm assuming these widgets are intended to be still functional. sorry if this is beating a dead envelope.

Fedora 24, Xorg, GNOME Shell 3.20.4

**Comment by Kingsquee** [comment]
likely related to #879

**Comment by mitchmindtree** [comment]
Hey @Kingsquee thanks for the detailed report!

Ahhh I see what's going on, it seems the `EnvelopeEditor` will always add a new point if the mouse is released anywhere over the editor that isn't over an existing point. This becomes particularly obvious when points are clamped between other points - as a result the point may no longer be under the mouse when the drag is released and so a new point is added. I'll fix this now so that a point is only added upon release if the release is not the end of a drag :+1: I think #879 is separate issue, but thanks for taking the time to have a look :)

**Comment by Kingsquee** [comment]
@mitchmindtree cool, np! what's the reasoning for having points be added on release instead of on press? I'd naively assume press is more intuitive.

**Comment by mitchmindtree** [comment]
@Kingsquee totally, now that you mention it I think you're right. I think I was subconsciously basing the design off an old audio plugin that I used to use, but inserting the point on left mouse press would feel much smoother! I'll have a play with this now.
