### ISSUE TITLE
Split piston feature for drawing with Graphics

### ISSUE THREAD

**Issue by Drakulix** [PistonDevelopers/conrod#888]
`backend::piston::draw` currently has no direct dependency on piston itself only on `piston2d-graphics`.
I am currently using conrod with a custom Graphics implementation that lives in an already initialized context. So I neither need `gfx` or `glutin`, but to get `backend::piston::draw` I have to enable the `piston` feature and pull the complete stack of dependencies into my otherwise very lightweight project.

I propose to move `backend::piston::draw` to a new backend module called `backend::graphics`, that only depends on a new feature `graphics`.

If you would accept a PR doing these changes, I would be happy to do it.

**Comment by mitchmindtree** [comment]
Hey @Drakulix, thanks a lot for the issue and sorry for the delayed response!

I think my preferred way of dealing with this would be to simply remove all of the piston modules other than the `draw` and `event` modules. I've discussed most of my reasoning behind this in [this comment](https://github.com/PistonDevelopers/conrod/issues/870#issuecomment-268986123). The TL;DR is that maintaining those extra modules is a significant amount of work for little gain. I'm aiming to push conrod towards a 1.0 alpha some time late next year and this will mean trimming down non-essential/ambiguous code.

**Comment by Drakulix** [comment]
@mitchmindtree Sounds reasonable and fixes this issue quite nicely.

Reading though #870 I got some questions. I am interested in the details of that issue, because I did choose to use `conrod` for my project, as it provides a completely platform agnostic way to represent an UI, that can be very easily adapted to work with other project.

While your proposed features are also favoring this design, reading through #870 gives the idea, that slimming down and stabilizing it even higher in the priority list and that slimming down the library to the point where it works with one API (e.g. `glium`) is at least considered a possibility to reach that goal.
I am not sure however, if I might have misunderstood something on my side.

Of course that would not happen very soon, but given the fact that `conrod` is related to `piston` and mostly aimed at game development, I am questioning if `conrod` is a good selection for my project.

To give you a little hint about what I am working on. I am developing a wayland compositor in rust, you might happen to know, that wayland uses OpenGL ES for rendering. So to provide an easy way to draw UI elements into my wanna-be Desktop Environment, I just forked `opengl-graphics` and plugged `conrod` into the rendering pipeline. I expected this to be far more complicated, but it took only about a day dealing with some opengl state assumptions of the original `opengl-graphics` library (I plan to release that fork btw).

I am sure this not a common use case for this library and I do not expect this use case to be supported at all. I did not even think I would work as nicely as it does.
But this libraries take on dependencies using only `piston2d-graphics` allows such a broad use, it would be a shame if any more hard-dependencies are introduced.

(This turned out to be far more text, that I anticipated, I hope you did not mind this little digression. I though giving some feedback on how this library can be used and is used, might be helpful/interesting.)


Back on the issue, I will most likely continue using piston anyway as long as possible, given the lack of alternatives.  :stuck_out_tongue_winking_eye:

How can I help speeding up this progress? Essentially what needs to be done, except for deleting the source code in question? What would I need to be aware of, if I wanted to submit a Pull Request regarding this issue?

**Comment by mitchmindtree** [comment]
> While your proposed features are also favoring this design, reading through #870 gives the idea, that slimming down and stabilizing it even higher in the priority list and that slimming down the library to the point where it works with one API (e.g. glium) is at least considered a possibility to reach that goal.
I am not sure however, if I might have misunderstood something on my side.

To be clear I'm absolutely planning on keeping conrod agnostic of the graphics and window backends. I also plan on continuing to support the piston2d-graphics and event conversion modules of the piston feature, as I feel these are unambiguously useful to all conrod+piston applications.

When I'm talking about slimming down I primarily mean w.r.t the event-loop and window wrapper stuff which currently exists within the piston backend module and this PR #871. As was mentioned in #870, it was originally designed to emulate the convenience of the [piston_window](https://github.com/PistonDevelopers/piston_window) crate but more suited to conrod use-cases, however it's a fair amount of code and is turning out to provide very little benefit over using the inner event-loop and window types directly and the code doesn't seem worth the maintenance and extra indirection.

It's not that I don't want conrod to be platform-agnostic anymore, it's more that I think conrod simply does not need the piston_window-esque stuff. Conrod by itself with `--no-default-features` should be capable of use with any graphics/event/window backend, however there would be work involved such as converting window events to conrod `Input` and displaying conrod `render::Primitives` to the screen. The `piston`, `glutin` and `glium` features are simply for removing this boilerplate when using conrod with their respective backends. I think eventually these might be moved out into their own crates (but still kept within this same repo) to make it easier for conrod itself to stabilise as all of those backends are currently pre-1.0. In the meantime it's much easier to work on and experiment with them as features.

When I'm talking about using glutin+glium, I'm mainly just talking about the examples - sorry if this was confusing! I'd like to do this for a few reasons:

1. they are quite simple window and graphics backends that don't require readers to grok complex generics. The users see the window and graphics contexts they're using directly without layers of abstraction/wrappers in between which can feel like a lot of indirection when hunting down upstream bugs or documentation. I also find it makes contributing upstream a little more tedious, as your fixes will inevitably take a little longer to propagate down to you with more crates in between you and the fix.
2. they currently perform significantly better than the piston backend, though the [graphics_tree crate](https://github.com/PistonDevelopers/graphics_tree) might help to improve this situation soon
3. they are pure rust and should "just work" with `cargo build` (don't require the user downloading and installing C libs like glfw or sdl2). winit (glutin) is obviously quite young compared to glfw and sdl2 and as a result still has quite a few bugs, however it is actively worked on and the maintainer plans on stabilising it within 2017 and I plan on contributing where I can.
4. they currently handle hidpi text rendering properly whereas there are still some artifacts using piston #787

> This turned out to be far more text, that I anticipated, I hope you did not mind this little digression.

No worries at all! This sort of feedback is a large part of the reason conrod has even made it this far 😸 

> Essentially what needs to be done, except for deleting the source code in question?

I'd like to hear @christolliday 's thoughts on #870 before moving ahead, otherwise I think the only other work is updating the examples, which I'd be happy to do.

**Comment by Drakulix** [comment]
That's all great to hear, watching #870 now. ;)

Please ping me, if I can help somehow.

**Comment by Drakulix** [comment]
Any Progress?

**Comment by mitchmindtree** [comment]
Yes I've made some progress on a local branch but have been busy with some contract work and other projects. I'll try to get around to this asap
