### ISSUE TITLE
Examples not working - DescriptorInit(PixelExport(0, None))

### ISSUE THREAD

**Issue by Attil** [PistonDevelopers/conrod#898]
Hi,

Whenever I try to run an example, the following error occurs:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(PixelExport(0, None))', ../src/libcore\result.rs:837
```
This is when I am working on a laptop. On my PC, everything works as it should. I tried using other OpenGL versions like 2.0, 3.0, 3.2 and 4.0 but it didn't help.

My laptop:
CPU: Intel i7
GPU: GeForce 780M
RAM: 16GB

**Comment by mitchmindtree** [comment]
Hey thanks for the issue!

Would you mind sharing which OS you're using?

Also, which examples specifically have this issue? E.g. `glutin_glium.rs` uses different window and graphics backends to `all_widgets.rs`, so knowing which will help to track down the bug. Especially as it seems to be graphics backend bug as this error type is not defined in conrod.

**Comment by Attil** [comment]
Thanks for the response!

I use Windows 8.1 on my laptop.

All examples except `glutin_glium` seem to have this issue.

The error occurs during a call to the `build()` method of `piston::window::WindowSettings`.

**Comment by mitchmindtree** [comment]
Hi @Attil, I'm going to close this as it sounds like the bug belongs upstream (it might be worth testing the [glutin_window crate](https://github.com/PistonDevelopers/glutin_window) or [gfx_graphics](https://github.com/PistonDevelopers/gfx_graphics) examples if you want to dig deeper).

Many of the examples have since been updated to use the backend that was working for you, so it might be worth trying to run them again.

If the examples at those repositories I mentioned work for you and you find that you're still running into bugs in the conrod examples, feel free to re-open this issue.
