### ISSUE TITLE
List rendering issue

### ISSUE THREAD

**Issue by Hyperchaotic** [PistonDevelopers/conrod#904]
Hiya,
I'm getting an issue with the List rendering if I change the dimensions in the list.rs example. I've changed window size to 440x400 and put the the list in its own cavas sized to 350x220. Item height 40 for the List.

I'm getting [this Window](https://dl.dropboxusercontent.com/u/1045037/Capture.GIF).

Example source [code here](https://gist.github.com/Hyperchaotic/d5846cdb4e7c41972f172da78fc9430b).

**Comment by mitchmindtree** [comment]
Hey @Hyperchaotic thanks for the issue :)

I finally got around to testing this - I adapted the current `list.rs` example by replacing the `set_ui` function with the one you give in the code example, adding the `list_canvas` to the `Ids` struct and changing the dimensions to 440x400 and it seems to work fine! Here is the window I get:

<img width="552" alt="screen shot 2017-01-31 at 7 53 39 pm" src="https://cloud.githubusercontent.com/assets/4587373/22458112/1954cb48-e7ef-11e6-9a5e-dc4f834bd66d.png">

Since you posted the issue, the example was switched over to use the "winit glium" features instead of the "piston" feature, so perhaps the issue had something to do with the scissor in the "piston" backend?

I'm going to close this for now as the code seems to be working fine when adapted to the current list.rs example - feel free to re-open if you still find yourself running into this issue!
