### ISSUE TITLE
`glium` backend: The `render::Primitive::Image` variant should not do gamma conversion and instead rely on the user selecting the appropriate glium `Texture` type for their image.

### ISSUE THREAD

**Issue by pedrocr** [PistonDevelopers/conrod#914]
It seems conrod is doing it's own sRGB gamma conversion when that should be the job of glium. Ideally that would be left to glium so you can do things like setup f32x3 RGB textures and let glium handle the displaying to the screen in the way that's best for the particular setup (e.g., doing 10bit per channel output when that's available).

**Comment by mitchmindtree** [comment]
I think this problem is specifically related to `Image`s implicit conversion from `gamma_srgb_to_linear` that occurs [here](https://github.com/PistonDevelopers/conrod/blob/master/src/backend/glium.rs#L633). We should instead be leaving this up to the user as glium provides [a variety of different `Texture` types for handling this properly](http://tomaka.github.io/glium/glium/texture/index.html). I believe the other primitives (`Text`, `Rectangle`, `Lines`, `Polygon`) will all still require the conversion. I'll update the title accordingly.

**Comment by pedrocr** [comment]
Now that I've been able to actually build an f32 glium texture this need becomes even clearer. Right now my image viewer is showing very clear posterization as I assume somewhere in the pipeline is doing LinearF32->LinearU8->GammaU8 losing all precision. So I'm not even sure the other primitives should do the linearization either but I haven't read the code yet.

**Comment by pedrocr** [comment]
See my comment in #926 for how this doesn't seem to be fixed yet. Somewhere the LinearF32->LinearU8->GammaU8 conversion or similar is still happening.

**Comment by mitchmindtree** [comment]
The image_button.rs example demonstrates the rust logo at 3 different colours and seems to render them correctly on my machine. Could you please share some code where this happens?

**Comment by pedrocr** [comment]
Sure, here's a minimal test case:

https://gist.github.com/pedrocr/9903c6d1f0d70133838465b921eb105f

**Comment by mitchmindtree** [comment]
OK, trying out your test case now!

First, attempting to compile this produced two compile errors:

```rust
error[E0308]: mismatched types
  --> gamma_bug.rs:39:69
   |
39 |   let raw_image = glium::texture::RawImage2d::from_raw_rgb_reversed(&imgbuf, (WIDTH,HEIGHT));
   |                                                                     ^^^^^^^ expected struct `std::vec::Vec`, found reference
   |
   = note: expected type `std::vec::Vec<_>`
   = note:    found type `&std::vec::Vec<f32>`
   = help: here are some functions which might fulfill your needs:
 - .to_vec()

error: non-scalar cast: `{integer}` as `f32`
  --> gamma_bug.rs:33:25
   |
33 |   let mut imgbuf = vec![0 as f32; (WIDTH*HEIGHT*3) as usize];
   |                         ^^^^^^^^
```

I fixed the first by passing the `imgbuf` directly (rather than via a borrow) and fixed the second by using `0.0` rather than `0 as f32`. After having fixed both of these, the code compiles but panics with the following:

```
thread 'main' panicked at 'Texture data size mismatch', /Users/Mitch/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.16.0/src/texture/any.rs:147
stack backtrace:
   1:        0x10f2764dc - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x10f277b5e - std::panicking::default_hook::{{closure}}::hce0d7336eef94718
   3:        0x10f277800 - std::panicking::default_hook::hd7b4c7a7e16abb43
   4:        0x10f277fb7 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   5:        0x10f1b8224 - std::panicking::begin_panic::h5871bdf0eba452a7
   6:        0x10f1e1f9c - gamma_bug::main::h03b4033bab5ee4f9
   7:        0x10f278e1a - __rust_maybe_catch_panic
   8:        0x10f278386 - std::rt::lang_start::h745bea112c3e5e1a
```

Does that code snippet compile and run successfully for you?
Out of curiosity, what version of rustc are you using? I'm using `rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)` for the record.
Could you provide a screenshot of how it looks for you?
Could you then also provide a screenshot of how it looks using an `SrgbTexture2d` rather than a `Texture2d`?

**Comment by pedrocr** [comment]
Ah, sorry, all those errors (except the cast) are because I've recently fixed some bugs in glium. Your fixes to the code are fine and to not crash you need glium from master. I'm using "rustc 1.14.0 (e8a012324 2016-12-16)". Here's a screenshot:

http://imgur.com/a/6ezGh

**Comment by pedrocr** [comment]
I don't seem to be able to use an SrgbTexture2d, conrod::image::Map doesn't take them

**Comment by mitchmindtree** [comment]
`conrod::image::Map` is generic and should take whatever glium texture type you give it when used with the glium feature. E.g. you can see the `image::Map` taking an `SrgbTexture2d` texture in [the image_button.rs example](https://github.com/PistonDevelopers/conrod/blob/master/examples/image_button.rs#L70).

Can you show me the compile error you're getting? To clarify, I'm talking about changing [this line](https://gist.github.com/pedrocr/9903c6d1f0d70133838465b921eb105f#file-test_gamma_rendering-rs-L40) to

```rust
let img = glium::texture::SrgbTexture2d::new(&display, raw_image).unwrap();
```

**Comment by pedrocr** [comment]
Indeed, I changed it in my own program and there I had two places that fed the Map so the compiler was complaining they didn't match. Using SrgbTexture2d does indeed solve this issue. It only requires me to go back to creating the image as gamma encoded but that's now a glium issue.

**Comment by pedrocr** [comment]
For future reference here's the fixed test case not using the SrgbTexture2d (and thus not doing gamma conversion back and forth):

https://gist.github.com/pedrocr/b59911210137bc32203c235e2b430aef

The issue was that I wasn't specifying the texture format so a bad default was being selected.
