### ISSUE TITLE
conrod::image::Map needs remove()/replace()

### ISSUE THREAD

**Issue by pedrocr** [PistonDevelopers/conrod#919]
I'm writing an image viewer with conrod so I create new images by reading them from the disk. Right now whenever I switch image I just use insert() to get a new conrod::image::Id and pass that on to widget::Image::new(). This works fine but I'm now leaking images. It would make sense to be able to have insert() and replace() methods so I can more easily keep the image map clean of old images I've since stopped using.

**Comment by mitchmindtree** [comment]
The only thing that stopped me from adding a `remove(id)` method originally was that the user may invalidate their `image::Id`s, and I was wondering if there might be some way we could avoid this... In reality, I think all we can do is either `panic!` if a user attempts to use an invalid `Id` with a useful message or simply not draw the image. Users will just have to be careful to not use `image::Id`s after their associated image data has been removed.

I'd be happy to accept a PR that added both of these methods, otherwise I'll try to get around to it myself soon.

**Comment by tl8roy** [comment]
Perhaps the image widget should return a result when ```set()``` is finally called?
That way the programmer can deal with it in the manner that they want to.

**Comment by mitchmindtree** [comment]
@tl8roy the `image::Id` isn't actually used by the `Image` widget during its instantiation so I don't think returning `Result`s here would help. The problem arises when the `Id`s are used to index into the map which doesn't occur until rendering.

Closed by #923.
