### ISSUE TITLE
ImageIds Initialisation

### ISSUE THREAD

**Issue by tl8roy** [PistonDevelopers/conrod#920]
I have a large struct of ```ImageIds``` that I need to initialise.

What is the best way of doing that at the moment?

The previous version used the ```widget_ids!``` macro but that doesn't apply any more.

Does a similar ```image_ids!``` macro need to be made?

**Comment by mitchmindtree** [comment]
@tl8roy the tricky part about making an `image_ids!` similar to a `widget_ids!` macro is that each `image::Id` has its own associated image data. I'm not sure how we can create an `image_ids!` macro that satisfies all of the following 3 requirements:

1. Declares a struct containing an `image::Id` field for each given identifier.
2. Does so at a module-level so that the type may be used from other modules.
3. Associates each `image::Id` with their specific image data which may be of any type in the `image::Map`.

The `widget_ids!` macro is particularly useful as we can generate a `struct` with a constructor that uses a `widget::id::Generator` to generate an `Id` for every field. I'm not sure how to do this in the case of `image::Id`s as the hypothetical `image::id::Generator` would need some way of mapping specific image data to each `image::Id`.

For now, I can only recommend doing something like the following:

```rust
let mut image_map = image::Map::new();
let image_ids = ImageIds {
    foo: image_map.insert(foo_image_data),
    bar: image_map.insert(bar_image_data),
    baz: image_map.insert(baz_image_data),
    //etc
};
```

I can imagine possibly introducing a new `image_map!` macro, similar to the old one that simplifies this construction a little, however this would only be useful to users who have a `struct` with a set of known images. Users who have some dynamic number of images stored in lists etc would still need some solution (though perhaps `image::Map::extend` is enough for these cases?).

Anyways, if you have any thoughts/ideas on improving this API or getting an `image_ids` macro working (or some other alternative) I'd love to hear them!

**Comment by tl8roy** [comment]
Good comment. 

I think probably what I am most after are examples for both use cases using the new ```image::Id`` structure.

As a (still) newish user of Rust, working out the best way to solve these issues is still a bit hard.

I can work with the example above and get it working for my own situation (Which is a static list of images).
For the Dynamic Images, a Hashmap might be the way to go.
