### ISSUE TITLE
[META] A place for discussions

### ISSUE THREAD

**Issue by suhr** [PistonDevelopers/conrod#934]
For example, [Gitter](https://gitter.im/).

**Comment by jabl** [comment]
There's the #rust-gamedev IRC channel (don't know if conrod users/devs hang out there though..)

**Comment by mitchmindtree** [comment]
I'm normally in the IRC channel @jabl linked while i'm at my computer :+1:

**Comment by mitchmindtree** [comment]
@jabl hey I just noticed I missed your msg on IRC! Feel free to open an issue if you need some help with something :+1:

**Comment by jabl** [comment]
Unfortunately it seems I missed out any potential answers to my IRC msg as well, since I was using the web IRC gateway I linked to above and I was of course disconnected the moment I closed the laptop lid. Guess I should use my irssi+screen setup that I'm using for other stuff..

Anyway, I think I figured out what the problem was. Or actually, it was two problems. I'm starting from one of the conrod examples, and I needed to avoid calling Display::wait_events() since that blocks waiting for some external event [*], secondly I had to call Ui::needs_redraw() after replacing my texture2d with a new texture.

[*] Or is there some way to push an event of my own into the event loop to cause, perhaps with some timer or such that would fire when it's time for my animation to switch to the next frame?

**Comment by suhr** [comment]
The problem with IRC is that you can come in a wrong time and there will be nobody ask questions to. People in #rust-gamedev usually talk about things that are not related to Conrod, and nobody reads IRC logs.

I'm actually have a conrod-related question, and looks like there's no place to ask it but right here.

I want to implement some kind of sequencer/DAW, so I have to implement a custiom piano roll widget. In Conrod, custom widgets constructed from primitives. But there's a problem: widget IDs.

Both [custom_widget.rs](https://github.com/PistonDevelopers/conrod/blob/master/examples/custom_widget.rs) and [primitives](https://github.com/PistonDevelopers/conrod/blob/master/examples/primitives.rs) examples specify *fixed* number of primitives with `widget_ids!` macro. But number of primitives in piano roll widget is obviously not constant. So this examples are not sufficient for my task.

So, how do I create a widget with variable amount of primitives? I know too little about Conrod and GUI programming in general to find a right solution.

**Comment by mitchmindtree** [comment]
> Or is there some way to push an event of my own into the event loop to cause it to wake up, perhaps with some timer or such that would fire when it's time for my animation to switch to the next frame?

@jabl if you create a `WindowProxy` (there should be a method on `Display` or the `Window` type returned by `Display::get_window` that does this), you can call [ `WindowProxy::wakeup_event_loop`](https://docs.rs/winit/0.5.10/winit/struct.WindowProxy.html#method.wakeup_event_loop) to insert a `winit::Event::Awakened` event. This way, you should be able to keep using `Display::wait_events` which is a little more efficient in terms of energy and CPU, rather than busy looping with `Display::poll_events` and `sleep`ing. If you want to discuss this further, feel free to open an issue!

> The problem with IRC is that you can come in a wrong time and there will be nobody ask questions to. People in #rust-gamedev usually talk about things that are not related to Conrod, and nobody reads IRC logs.

@suhr It is for this reason that I prefer people open new issues here if they have questions, rather than asking in IRC or gitter. It also means that questions are well documented for future users who may run into similar issues.

> Both custom_widget.rs and primitives examples specify fixed number of primitives with widget_ids! macro. But number of primitives in piano roll widget is obviously not constant. So this examples are not sufficient for my task.

[This comment](https://github.com/PistonDevelopers/conrod/issues/826#issuecomment-246083132) describes how to dynamically generate widget identifiers. I think you're right - we should have an example that demonstrates this. I'll try to get around to adding one next time I get a chance.

In case you're interested, here's a pic of my own timeline widget  that features a piano roll track. I'm hoping to open source the crate, however it is currently a little integrated into a private project and it will take some time to separate, so I can't give any time frame on availability just yet.

![screen shot 2016-11-24 at 5 07 02 pm](https://cloud.githubusercontent.com/assets/4587373/22770737/d0459974-eee6-11e6-8e1b-cb545d0ce0d6.png)

I'm going to close this issue now as I don't have the time to track any more places for discussing conrod. For future readers, please feel free to post an issue with your question as I'm much more likely to see it that way. Otherwise if you want to try and catch me in person I'm normally in #rust-gamedev whenever I get a chance.
