### ISSUE TITLE
Antialiasing of primitives

### ISSUE THREAD

**Issue by sp-1234** [PistonDevelopers/conrod#967]
Is it possible to enable or are there plans to make it possible?

Right now, "primitives" example clearly doesn't use antialiasing, because lines that aren't parallel to 0/45/90 degrees look jagged. (especially visible on ellipses)

![screen shot 2017-04-06 at 10 22 24-or8](https://cloud.githubusercontent.com/assets/19407943/24742697/02c50134-1ab4-11e7-9924-4bcdb9ebe8be.png)

BTW, if that matters, the GPU which I used to run the example is known to support antialiasing in OpenGL.

**Comment by mitchmindtree** [comment]
Thanks for the issue!

This has been on the back of my mind since adding the `glium` backend, however I haven't had the time for it. The `glium` crate [has an example of how to implement fxaa](https://github.com/tomaka/glium/blob/master/examples/fxaa.rs), so it shouldn't be too tricky to adapt if someone wanted to go ahead and implement this. Otherwise I'll probably have a go in the distant future, however I'm not sure when as it is pretty low on my priority list.

**Comment by sp-1234** [comment]
FXAA is a purely post-processing technique, it doesn't improve positional precision, just tries to fix what's already drawn. Therefore it also can accidentally butcher some details.
Maybe it's better to "simply" enable regular multisampling (https://www.khronos.org/opengl/wiki/Multisampling)

**Comment by mitchmindtree** [comment]
Ah my mistake, thanks for the info!

It looks like all we have to do is set the [multisampling param in `DrawParameters` to true](https://github.com/tomaka/glium/blob/057f0ebcd7bd92240cf09186d84d298d0d65b2e8/src/draw_parameters/mod.rs#L296) and then the user can call [`.with_multisampling(n_samples)`]((https://docs.rs/glutin/0.7.4/glutin/struct.WindowBuilder.html#method.with_multisampling)) when [building their glutin window](https://github.com/PistonDevelopers/conrod/blob/master/examples/primitives.rs#L36).

I'll do a PR for this now as it looks to be an easy fix :+1:
