### ISSUE TITLE
Elements disappearing as other elements moved on the screen

### ISSUE THREAD

**Issue by dpzmick** [PistonDevelopers/conrod#977]
I've been toying with conrod for a graph editor and run into a few problems.

Here's a video: https://www.youtube.com/watch?v=hFjDwWOZjYc

Here's the code: https://gist.github.com/dpzmick/66536505f08ac0d26736938f44633f34

Essentially, I find it surprising that some of my lines seem to disappear as I drag these rectangles around the display. This only happens when moving the rectangle which is added first.

**Comment by mitchmindtree** [comment]
Hmmm I'm not sure what could be causing this at first glance, though it might have something to do with using the `Line::new` constructor. Changing it to `Line::abs` fixes it for me. The difference between the two is that `Line::abs` automatically sets the bounding box for the `Line` from the given absolute positions, whereas `new` requires manually specifying the position and dimensions with builder methods. The `Line` constructors are currently quite confusing and fixing them with clearer names has been on my mind for a while.

You might also want to set the `.depth(f)` of the `Line` - otherwise it will be drawn on top of the rectangle and will make it trickier to pick the rectangles with the mouse.

Hope this helps!

**Comment by dpzmick** [comment]
Yep! This solves the problem. I'll go ahead and close this issue since I'm not sure there's a legitimate issue; I've just misused the api.

Thanks for your help
