### ISSUE TITLE
Launching the built exe on windows doesn't open the window

### ISSUE THREAD

**Issue by radonthetyrant** [PistonDevelopers/conrod#987]
I compiled a small app that displays the hello world example as a base of my project development.

If I run `cargo run` everything works as expected.

If I build the project with `cargo build` or `cargo build --release` and try to run the exe, a console window appears without any output, but the window does not appear.

Version info:
```
$ rustup show
Default host: x86_64-pc-windows-msvc

stable-x86_64-pc-windows-msvc (default)
rustc 1.17.0 (56124baa9 2017-04-24)
```
`Microsoft Windows [Version 10.0.15063]`

**Comment by mitchmindtree** [comment]
Hmmm I wrote some GUI stuff for a scoreboard company using conrod on windows 10 a month or two ago and haven't run into any issues with opening windows from what I remember.

Do you run into the same issue when compiling and running the conrod examples? Can you show me the command you're using to run the exe?

Is your `assets/` directory accessible to the .exe? I believe the examples search for the assets directory relative to the current directory (probably not the best idea), so `cd`ing into `target/examples/release` and running `./my_example` might not work, while `cd`ing into the project root (the directory with the `Cargo.toml`) and running `./target/release/examples/my_example` *should* work.

By the way, if you'd like to build a GUI app so that the terminal window doesn't open, you can use this command:

`cargo rustc --bin my_app --release -- -Clink-args="/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"`

It might not help with the current issue, just thought I'd share in case you run into a need for it!

Hope some of this helps!

**Comment by radonthetyrant** [comment]
the missing asset directory may indeed be the culprit, i didnt think of making it available for the exe as well. i thought it might be included as a resource or something similar to dotnet

**Comment by mitchmindtree** [comment]
Ahh that was likely it then!

In case it helps, this is how I normally find the `assets` directory in my personal conrod projects.

```rust
    // Find the assets directory.
    let exe_path = std::env::current_exe().unwrap();
    let assets = find_folder::Search::ParentsThenKids(7, 3)
        .of(exe_path.parent().unwrap().into())
        .for_folder("assets")
        .unwrap();
```

The `find_folder` crate is a simple crate used for searching relative directories for a folder with the given name.

Do you mind if I close this issue now? (you're also welcome to do so yourself)

**Comment by radonthetyrant** [comment]
Yes, thanks for your help! Appreciate it
