### ISSUE TITLE
Split Canvas

### ISSUE THREAD

**Issue by AlexCreamer** [PistonDevelopers/conrod#990]
Hi, I have a canvas that has two canvas' that get placed onto it. One of the canvas' has an image that gets placed onto it but theres a problem where if the image is large enough it will extend over to the second canvas. How can I have two canvas' in a canvas so that the image doesn't cross over the other canvas?

**Comment by mitchmindtree** [comment]
Hmm one fix might be to call `.crop_kids()`  on the `Canvas` that is the parent of the `Image`. This should crop the image to the bounds of the `Canvas`. Is this what you're looking for? Otherwise if you want to *resize* the image to the size of the parent `Canvas`, you could call `.wh_of(ids.parent_canvas)` on the `Image` widget.

Hope this helps!

**Comment by AlexCreamer** [comment]
Hi Mitch,

Thanks a lot for the response! .wh_of solved that problem for me, but it lefts me with a different problem. I have a script that measures the height and width to use for the image and to use those measures. My problem (I assume) is that the height of the image becomes too large for the canvas. Is there a way I can length of a canvas so that I can use that as a maximum?

**Comment by mitchmindtree** [comment]
No problem! You can get the dimensions and position of a widget in a variety of forms via the `Ui::rect_of` method. E.g. `ui.rect_of(ids.parent_canvas)` returns an Option<[Rect](https://docs.rs/conrod/0.52.0/conrod/position/rect/struct.Rect.html)>.

**Comment by AlexCreamer** [comment]
Thanks again, especially for the given example.
